### ISSUE TITLE
Set up API documentation generation

### ISSUE THREAD

**Issue by samsontmr** [OpenMined/PySyft#120]
Now that our codebase is growing (hooray!), we can start thinking about setting up a pipeline to generate nice API docs for Data Scientists. [Matplotlib](http://matplotlib.org/contents.html) has fantastic documentation, we could use them as inspiration

**Comment by cypherai** [comment]
Agreed 🙂 How about using [sphinx](sphinxdocs.com) or [mkdocs](mkdocs.org)?

**Comment by samsontmr** [comment]
Heard of sphinx but not mkdocs! Pros and cons? Something to consider as well would be whether it supports JS (we should *try* to use the same tools across components).

**Comment by cypherai** [comment]
I'm only familiar with `mkdocs`. I think it has only basic features compared to `sphinx`. However, some major projects use it to generate docs automatically.

I would suggest that we take a look at what `Keras` does with it:

- https://keras.io
- https://github.com/fchollet/keras/tree/master/docs

**Comment by samsontmr** [comment]
Wow! it looks pretty nice too

GitHub is wonky lol.
![capture](https://user-images.githubusercontent.com/15007950/29241404-b3093400-7fab-11e7-8bd0-acbcf58b83b1.PNG)

**Comment by Edvac** [comment]
Sphinx is nice. I am using it to document my code. I like the autodocs (auto generated documentation from comments in the code). I think Sphinx is a nice choice because it is under active development. [github repo](https://github.com/sphinx-doc/sphinx/commits/master) and also it is used as well in big projects
[examples](http://www.sphinx-doc.org/en/stable/examples.html). It has also some tutorials on youtube that can help.

**Comment by samsontmr** [comment]
@Edvac thanks for the input! I quite like the autodocs feature too :P

**Comment by Edvac** [comment]
I think so too. It seems more robust than other generators.
There are quite a few cool documentation generators like

- [natural docs](http://www.naturaldocs.org/)

- [dexy](http://www.dexy.it/)

- [doxygen](http://www.stack.nl/~dimitri/doxygen/)

But they are not currently under development or as much as sphinx.
This site can give you an nice insight:  [javascript documentation](https://js.libhunt.com/categories/19-documentation) . 
(Although it is about javascript documentation it includes also general tools like sphinx.)

Sphinx seems to be one of the most used. That's why I decided to use it.
If anyone uses something else it would be nice to enlighten us. :-)

Also I think is good to have in mind what we want to document.
as you said @samsontmr   " Set up API documentation generation"
Sphinx we could say is also a "General purpose open source documentation tool". While tools like 

1. [raml](https://raml.org/)
2. [swagger](https://swagger.io/)
3. [apiblueprint](https://apiblueprint.org/)

are suitable for only api documentation.

These are two nice thoughts about the types of documentation.

- [stackoverflow](https://stackoverflow.com/questions/12537/what-tools-are-used-to-write-documentation)

- [Yevgeniy Brikman blog post](http://www.ybrikman.com/writing/2014/05/05/you-are-what-you-document/)

So I think, if the question is only for "Set up API documentation generation". Sphinx would be a wise choice but there are also tools that are focused specificaly on API documentation.

**Comment by nikonoll** [comment]
Random new guys opinion here:
As @Edvac already hinted at the subject of pure API documentation differs from just general doc generation. From personal experience I can only recommend swagger and it's UI [demo](http://petstore.swagger.io/) since it can deliver a truly interactive API exploration experience and enforces correctness of documentation. It achieves this by actually having models for request/response (including data types, nested objects etc.) that can be tested from withing the documentation.

**Comment by nathanielcompton** [comment]
Has there been any movement on this issue? If not, I'll get to work.

**Comment by iamtrask** [comment]
Epic! Can't wait to see it!

**Comment by bharathgs** [comment]
@nathanielcompton any updates on this?
