### ISSUE TITLE
Implement the inline Bernoulli function for IntTensor on the GPU

### ISSUE THREAD

**Issue by alberduris** [OpenMined/PySyft#1277]
As a Data Scientist using PySyft's IntTensor type, I want to leverage a wide range of methods which use our new Unity backend. For this ticket to be complete, the inline GPU implementation of bernoulli() should be added to our IntTensor class with the appropriate functionality.

Note, it is possible that when you look in the code you'll find that parts of this issue were completed on the backend while implementing another issue. This is normal as features do not live in isolation. If this is the case, just take it as a convenience that someone already built that part and press on!

### Every Reference You Might Need for this Issue:

- For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.
- For a reference on how to program in Unity, check out [this basic tutorial](https://unity3d.com/learn/tutorials/projects/roll-ball-tutorial)
- For a reference on how to write HLSL code, check out [this basic tutorial](http://kylehalladay.com/blog/tutorial/2014/06/27/Compute-Shaders-Are-Nifty.html)
- For a complete tutorial on how to add functions to FloatTensor (step by step guide) see [this Google Document](https://docs.google.com/document/d/1WRd7gGLFN0Awtf86AICYIHtg3gfFWLBa5wYTthsB3i0/edit)
- For a reference on how other functions like this have been implemented check out the functions in [this notebook](https://github.com/OpenMined/OpenMined/blob/master/notebooks/Syft%20Tensor%20Example%20Notebook.ipynb) as well as the corresponding files that made it possible ([SyftController](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs), [FloatTensor.Ops](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs), [FloatTensorShaders](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/FloatTensorShaders.compute), [TensorOpsShaders](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/TensorOpsShaders.compute), [FloatTensorTest](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorTest.cs) and [FloatTensorGpuTest](https://github.com/OpenMined/OpenMined/blob/master/UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorGpuTest.cs)).
- And of course, please consider our [Contributor Guidelines](https://github.com/OpenMined/Docs/blob/master/contributing/guidelines.md) for all contributions.

### Acceptance Criteria:

- [ ] comment below that you're picking up this project
- [ ] an example in a notebook in our [tests folder](https://github.com/OpenMined/OpenMined/tree/master/notebooks/tests) showing how to use the functionality from PySyft
- [ ] an integration test in PySyft demonstrating the correct CPU operation implemented over an IntTensor while connected to a Unity backend
- [ ] a Unit Test in OpenMined/OpenMined demonstrating the correct operation on a FloatTensor
- [ ] [inline](http://pytorch.org/docs/master/tensors.html) documentation in the python code. For inspiration on inline documentation, please check out PyTorch's documentation for this operator.
- [ ] Link your Pull Request back to this Issue so that it gets closed appropriately when the PR is merged.

**Comment by chunduri11** [comment]
I am taking up this issue

**Comment by jvmancuso** [comment]
I have some confusion with this issue.

Firstly, wouldn't a `.bernoulli` method be better on FloatTensor?  For example, PyTorch's [`torch.bernoulli`](http://pytorch.org/docs/master/torch.html#torch.bernoulli) function inputs a FloatTensor or DoubleTensor, where each element is assumed to represent the parameter `p` (in [0,1]) of a separate Bernoulli distribution.  Then the _output_ tensor could be coercible into an IntTensor, or perhaps more sensibly a ByteTensor, with each element being either {0,1} and sampled from the corresponding distribution.  This means this method should be part of FloatTensor, and not IntTensor.  I recommend modifying the name of each of the issues associated with this method, as it's currently misleading.

Additionally, I'm a little confused about how autograd will work for these methods.  From my (limited) understanding, the autograd engine currently only allows for differentiation on deterministic nodes of a computation graph.  However, implementing this method would introduce random variables into the computation graph, making it stochastic.  @iamtrask and I have been talking about extending autograd to stochastic computation graphs (see OpenMined/OpenMined#382), but from our understanding it's not feasible within the current implementation.  Perhaps we should backlog this until that's done.  Another option could be to write the method to raise an exception when you try to call `backward` on a graph that contains the bernoulli operation.  Will defer to others on this though, just thought I'd raise the issue here.

**Comment by jeamick** [comment]
@alberduris an update about @jvmancuso  question ?

it sounds good yep nope ?

**Comment by jvmancuso** [comment]
Hey @jeamick, we decided not to extend autograd to include stochastic computation graphs, but that doesn't mean this issue should be abandoned.  We'll be assuming users are aware of the risks of introducing random variables, and we wanted to provide something similar to [torch.distributions](http://pytorch.org/docs/master/distributions.html) in the future, although tensors in PySyft need to be a bit more feature complete before that can happen.

However, the first part of my comment still stands.  If anyone's going to implement this, it should be for FloatTensor.
