### ISSUE TITLE
Fix up special case of overloading __repr__ to print big tensors

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/PySyft#1367]
Child of OpenMined/Grid#171 and OpenMined/Grid#190 (see those and their discussion for reference/instructions)

**Comment by LaRiffle** [comment]
From the stacktrace below obtained when printing which involves `new___repr__`, it seems that the problem is caused by `row[-truncate:]` which uses the `select()` method on a Tensor, (which we haven't rewritten as it is in the `self.exclude` of the hook) 

`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/Users/ryffel/Documents/Code/PySyft/syft/core/hooks.py", line 622, in new___repr__`
`    return self.old__repr__()`
`  File "/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 144, in __repr__`
`    return str(self)`
`  File "/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 151, in __str__`
`    return _tensor_str._str(self)`
`  File "/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 297, in _str`
`    strt = _matrix_str(self)`
`  File "/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 246, in _matrix_str`
`    strt += __repr_row(row, indent, fmt, scale, sz, n)`
`  File "/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 202, in __repr_row`
`    ' '.join(fmt.format(val / scale) for val in row[-truncate:]) +`
`  File "/Users/ryffel/Documents/Code/PySyft/syft/core/hooks.py", line 298, in send_to_workers`
`    if self.is_pointer:`
`AttributeError: 'torch.FloatTensor' object has no attribute 'is_pointer'`

Can't we just fix this by modifying the `new___rpr__` as follows ?

`def new___repr__(self):`
`      _id_in_owners = hook_self.local_worker.id in self.owners`
`      if (hook_self.local_worker in self.owners or _id_in_owners):`
          **tensor_type.is_pointer = False**
`          return self.old__repr__()`
`      else:`
`          ...`

It fixes the basic examples given in the related issues, and passes tests, but I not sure it is ok in general.
