### ISSUE TITLE
Question: Where is the federated learning Code?

### ISSUE THREAD

**Issue by setsometso** [OpenMined/PySyft#1465]
....here should be a example code of federated learning, but i cant find it. Why did you guys delete it?
Where can i find it?

**Comment by iamtrask** [comment]
We only moved it because now we have several different examples :) 

A Toy Example (the one you saw before)
https://github.com/OpenMined/PySyft/blob/master/examples/toy/Federated_Learning_Example.ipynb

A Bigger Example
https://github.com/OpenMined/PySyft/blob/master/examples/SocketWorker%20Boston%20Housing%20Client.ipynb
