### ISSUE TITLE
Performance analysis of PySyft

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1479]
# Context
 We're x100 slower than PyTorch, where do we loose time?
Some brutal profiling may help 💪 
Example on Boston Housing (25s instead of 0.25s) : https://colab.research.google.com/drive/17upxCYJmJ6Zoxv0KjiJ1ZbchlJybsfhs

**Comment by jvmancuso** [comment]
I completed a small analysis regarding iterated add operations [here](https://github.com/jvmancuso/PySyft/tree/speedtest/examples/experimental/grid_benchmark) to get a sense of how things have changed since we started the original hooking project on Grid.  Not sure how useful of a comparison this is, but I figure it's worth getting a conversation started 😄

**Comment by souravsingh** [comment]
I would like to take a stab at the issue. Where do I start?
