### ISSUE TITLE
Base Worker Command Statistics

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1602]
BaseWorker classes have a bottleneck send_msg() function which all commands are sent through. We would like to be able to optionally track statistics about commands being sent. In particular, we would like to optionally be able to track how many messages are sent to-from particular workers, of a particular message type, and track statistics like "completion time". 

This project is about implementing a first version of this kind of statistical tracking which should greatly help us with optimizing the system as well as understanding general performance characteristics and constraints.

**Comment by replomancer** [comment]
I'd like to do this.

**Comment by iamtrask** [comment]
It's all yours!

**Comment by kamathhrishi** [comment]
I don't think this has been completed yet right?

**Comment by replomancer** [comment]
Well, this issue is about "first version of (...) statistical tracking". I've written something for start and my PR has been accepted. I don't know if people use it and what they think about it. There's always room for improvement, but I found it hard to do better without more explicit requirements.

I would close this issue and create new ones if there are more concrete ideas for statistics-related features.

**Comment by kamathhrishi** [comment]
Alright then.

**Comment by iamtrask** [comment]
Sounds good!

**Comment by iamtrask** [comment]
One good follow-on project might be to report statistics to the notebook as an option (right now it only writes to a file). Another might be more statistics relating to message size, number of messages, etc.
