### ISSUE TITLE
Should we keep adding attributes to `torch` ?

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1707]
Related to #1587

In our previous version, we added, especially in https://github.com/OpenMined/PySyft/blob/master/syft/core/frameworks/torch/__init__.py , many elements to the module torch.

I'm wondering if we should keep this approach, which is not very elegant and raises relevant warnings in PyCharm. What better solution could we think of?

**Comment by Nivek92** [comment]
I am against adding attributes to torch itself.
Like you said it's not very elegant and I would argue actually bad practice.
It would make more sense to add it to the TorchHook or create a separate object which just holds the required attributes.
On the same note I think it makes sense to split the hook.py into multiple files as it's quite long.

**Comment by iamtrask** [comment]
I'm a fan of moving everything to the hook - however the hook itself will still need to be added to "torch".

The problem is that occasionally PyTorch is responsible for initializing new torch tensors, which means we cannot pass in our own hook in the constructor (so that all initialized tensors will have a proper .owner attribute, for example). The only way to get them to have an owner is to have a default when one is not specified, the reference to which needs to be stored in the global namespace somewhere that torch constructors can always access. I'm definitely PRO figuring out a better way to do this, but I'm not aware of any solutions at the moment.

**Comment by LaRiffle** [comment]
Ok so the most straightforward option would be to make an object storing all our stuff and adding that object to torch. Or maybe we could add it to `syft` instead ?

**Comment by iamtrask** [comment]
Perfect! - oh oh oh -  adding to syft is a much better idea!

**Comment by Ogofo** [comment]
Is this discussion still open or solved by #1706? If so, please close :)
