### ISSUE TITLE
Reduce duplication in serde test logic

### ISSUE THREAD

**Issue by Nivek92** [OpenMined/PySyft#1740]
At the moment there are two different test cases for uncompressed/compressed serialization even though they only differ by the flag for compress & compressed.

**Comment by amit-rastogi** [comment]
Hey @Nivek92 I'm picking this up.

Update the following test cases to reduce redundancy-
test_compress_decompress_lz4
test_compress_decompress_zstd
test_compressed_serde_lz4
test_compressed_serde_zstd

**Comment by Nivek92** [comment]
There is still duplicate code though e.g.
compressed = _compress(original)
decompressed = _decompress(compressed)

compressed = _compress(original, "zstd")
decompressed = _decompress(compressed, "zstd")

these are 4 lines while we could also do

for attr in ["lz4","zstd"]:
  compressed = _compress(original, attr)
  decompressed = _decompress(compressed, attr)

**Comment by Ogofo** [comment]
Regarding the open PR #1753, I suggest to refactor the test to use `@pytest.mark.parametrize()` annotations to the multiple test cases. Before implementing this, we have to resolve the issue that comes with class methods that inherit `unittest.TestCase`. Unit tests are not allowed the have arguments passed to a method. 

I'm not sure if there is a deeper meaning to those classes other than grouping the test cases. I would suggest to let the classes inherit from `object` if one wants to keep the grouping. Otherwise, I would suggest to 

(@robert-wagner mentioning you here as you reviewed the specific PR)

**Comment by amit-rastogi** [comment]
Do we need to add pytest in requirements.txt?
