### ISSUE TITLE
Increase Test coverage to fail under 100

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1786]
Currently test coverage is set to fail under 95 percent. We should try to have tests for everything and manually exclude (using #pragma: no cover) functions or sections of functions which we do not want tested. This gives intentionality to what we are and are not testing.

**Comment by robert-wagner** [comment]
@LaRiffle @Nivek92 @Ogofo @iamtrask Would appreciate your feedback on this

**Comment by LaRiffle** [comment]
I've been working on having a very high coverage, however at some point you end make a stupid test just to cover a single line which really doesn't gives you much. I'm a bit cautious about using quotes #pragma because it makes the code less readable
I think you can go up to 97% but I would prefer that we spend time doing tests that are really relevant and writing code :)
