### ISSUE TITLE
Integrate with Moment's Accountant from Abadi et al.

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1932]
With the SensitivityTensor integrated, now we want to integrate it with the concepts described in Abadi et al.'s MomentsAccountant technique (for reference there are example implemenations https://github.com/LaRiffle/differential-privacy/tree/master/privacy_accountant).

Specifically, we want to make it so that we can automatically track privacy budget using the output . of SensitivityTensor. The output demo of this work should be a DP-SGD optimizer which correctly calculates the budget (note that we should have unit tests showing that it works correctly - unit tests should be checked against output from the reference implementations linked above)

**Comment by joeddav** [comment]
Does this issue depend on #1928? If not, I'd be interested in tackling it.

**Comment by joeddav** [comment]
I'm looking into this, but am running into the problem that there's no good way of getting unaccumulated batch gradients in PyTorch. That is, you can't get and clip the gradient of each individual data point without calling `.backward` separately for each. See the discussion here from someone else that ran into the same issue:

https://stackoverflow.com/questions/53798023/computing-gradients-for-every-individual-sample-in-a-batch-in-pytorch

Unless we can figure out a way to get unaccumulated gradients, the optimizer will have to work with an effective batch size of 1 from an efficiency perspective. Otherwise, there's no way to clip gradients from individual data points.

**Comment by 9310gaurav** [comment]
Why can't we use micro-batching as mentioned in this paper : https://arxiv.org/pdf/1812.06210.pdf ?

**Comment by jvmancuso** [comment]
>That is, you can't get and clip the gradient of each individual data point without calling .backward separately for each.

Have you looked into the semantics of the torch.autograd.backward function? I believe they allow for this via the grad_tensors kwarg: https://pytorch.org/docs/stable/autograd.html

A more approachable blog post about how to interpret what the vector in a Jacobian vector product represents: https://towardsdatascience.com/pytorch-autograd-understanding-the-heart-of-pytorchs-magic-2686cd94ec95
