### ISSUE TITLE
Create interface for objects able to send and catch tensor operations

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2079]
As discussed at #2068:

>  *The reason why it (Plan) was a worker is that we needed to use the functionality to catch function and method calls on torch tensors, just the way it is done by workers sending commands between each other*

In the future is possible that this functionality could be useful for other non-worker objects. I suggest that we create an interface that implements this and a worker implements this interface.

**Comment by mari-linhares** [comment]
@LaRiffle any idea about how to make this work? I've tried for a bit, but I'm having a hard time.

I think the problem is the ways plans are built ([more specifically line 146](https://github.com/OpenMined/PySyft/blob/cd4d6e985c03b9cf57b784c4f49eed47e116bbda/syft/workers/plan.py#L146)). Any ideas or suggestions?

**Comment by LaRiffle** [comment]
So maybe what we could do is, instead of recreating a worker of each plan, to use the plan owner. 
Example:
you have a plan f and some data x, which you all send to bob. F is unbuild. When you do f(x) the first time, you tell bob "Hey, the next commands you'll get should be stored in the my plan f", you run the commands in f, and then "Ok bob, now build the plan with those commands and run it", and you and him set the plan to "built". The second time (or the first time if you sent your plan f already built), when you do f(x2), actually you say to bob "Hey, remember f? Give him my x2 and run it".

This way you relie on Bob ability to catch calls, and plan appear more like what they should be: benign objects, which can be stored by workers and can have Pointers referencing them (in line with #2096)

**Comment by mari-linhares** [comment]
Right now, I feel like we can treat each specific case differently like was done in #2098.
