### ISSUE TITLE
classification error

### ISSUE THREAD

**Issue by keenlykeenly** [OpenMined/PySyft#2332]
![image](https://user-images.githubusercontent.com/11493656/60638150-cff42600-9e4f-11e9-8a31-7b34084f636a.png)

The execution in part13 is OK, but the classification results are wrong. How can I fix it? Thank you very much.

**Comment by mari-linhares** [comment]
Hey @keenlykeenly,

I don't think this is an issue since the model is randomly initialized it's possible that it could classify the first images wrong. Having said that I'll close the issue for now.

But maybe is not a coincidence that it classified all images as zeros, have you trained the model? Can you check how your model classifies other images from the test set?

Thanks!
