### ISSUE TITLE
Eliminate GetShapeMessage When PyTorch Will Allow It

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2513]
**Describe the solution you'd like**
We have a GetShapeMessage type which is a message type which is specific to PyTorch. All message types should strive to be framework agnostic, so we'd like to eliminate this for a ObjectRequestMessage message type instead.

This issue is referenced as a TODO in https://github.com/OpenMined/PySyft/blob/dev/syft/messaging/message.py

**Describe alternatives you've considered**
We could leave it.

**Comment by karlhigley** [comment]
The semantics of ObjectRequestMessage don't lend themselves nicely to this use case either, because ORM indicates that the worker should delete its copy of the tensor after sending it back.

The comment that led me here says:
```
# TODO: remove this message type and use ObjectRequestMessage instead.
# note that the above to do is likely waiting for custom tensor type support in PyTorch
# https://github.com/OpenMined/PySyft/issues/2513
```

PyTorch now has some kind of custom tensor type support, but I'm not sure what that has to do with GetShapeMessage. Any idea?

**Comment by iamtrask** [comment]
Don’t delete this yet. We need it for pointertensor

**Comment by karlhigley** [comment]
Sure, I'm not in a hurry to remove it, I just want to understand what's going on here and the comments don't entirely spell it out. Based on the keywords `.shape`, `PointerTensor`, and "custom tensor type support", I'm guessing that the issue might be that calling `.shape` on a `PointerTensor` doesn't quite work due to limitations in PyTorch and this message is a workaround for that?

**Comment by iamtrask** [comment]
Exactly (forgive brevity I’m replying via email on my phone)
