### ISSUE TITLE
Automatic Typing for Default Message Detailer

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2514]
**Is your feature request related to a problem? Please describe.**
At present, the default detailer for Message (an abstract type) returns an object of type Message instead of returning an object of the correct type.

**Describe the solution you'd like**
Use the msg_tuple[0] to look up the correct type.

**Describe alternatives you've considered**
Return NotImplementedException instead and require all Message types to have their own detailers.

**Comment by PlamenHristov** [comment]
I think this issue requires some clarification. From what I understand `Message.simplify()` and `Message.detail()` should be inverses of each other. However, I don' think that's exactly what's happening. If we consider the test below: 

```
def test_message_detail_returns_specific_type():
    tensor = th.tensor([1, 2, 3, 4])
    operation = message.Operation(
        cmd_name="_add__",
        cmd_owner=tensor,
        cmd_args=(tensor,),
        cmd_kwargs={},
        return_ids=96100376575,
    )

    wrapped = message.SearchMessage(operation)
    simplified_operation = message.Message.simplify(sy.local_worker, wrapped)
    detailer = detailers[simplified_operation[0][0]]
    detailed_operation = message.Message.detail(sy.local_worker, simplified_operation)

    assert isinstance(detailed_operation, message.Operation)
```
when [Message.simplify()](https://github.com/OpenMined/PySyft/blob/fd16c9ada84e6df9a7293db8b3a6dd6df109e128/syft/messaging/message.py#L65) takes the contents of `wrapped`, because it reads the `wrapped.contents`, it effectively removes the knowledge of the `SearchMessage` object and returns directly the `Operations` object. 

![image](https://user-images.githubusercontent.com/3893599/71752174-cf802a80-2e86-11ea-96a4-662ef9ce6acd.png)

Next when the simplified object gets passed to [Message.detail()](https://github.com/OpenMined/PySyft/blob/fd16c9ada84e6df9a7293db8b3a6dd6df109e128/syft/messaging/message.py#L91) it only has info for the `Operations` object thus the only thing it can do is wrap it in a `Message` object.

There are two ways to approach this and have a "fix" for the issue. Either:

- Don't take the contents of the message on `Message.simplify()`, but the whole `ptr`

- Keep `Message.simplify()` the same, but have something like the below code in `Message.detail()`  
```
 obj = sy.serde.msgpack.serde._detail(worker, msg_tuple[0])
        if isinstance(obj, Message):
            return obj
        return Message(obj)
```

Let me know your thoughts.

**Comment by PlamenHristov** [comment]
Ok I can see those methods will be deleted https://github.com/OpenMined/PySyft/pull/2826. Nvm.

**Comment by karlhigley** [comment]
@PlamenHristov #2826 won't be merged, so I think this is still relevant.
