### ISSUE TITLE
Supported Layer List

### ISSUE THREAD

**Issue by hezhangsprinter** [OpenMined/PySyft#2542]
Hi
   Thanks for the great work !! 
    Is there any list of the layer that has been hooked with pytorch? 
    Is torch._C._nn.avg_pool2d supported ?

**Comment by LaRiffle** [comment]
Not exactly, by default we provide a generic behaviour for all layers, but sometimes it doesn't work as expected and we need to add specific mechanisms. This happens when people find out they need smthg which doesn't work as expected.

So maybe check if you can use it, and if it fails miserably because of that specific component, then throw an Issue about this and we'll get it fixed :)
