### ISSUE TITLE
Why does Input to Model requires gradient when using Secure MPC.

### ISSUE THREAD

**Issue by sanvenDev** [OpenMined/PySyft#2618]
**Describe the bug**
When we share the model and data to different virtual workers, then obviously it's the Model whose requires_grad should be True and data's requires_grad should be False, but when I pass this data which doesn't requires gradient to the model, I get following error:
"RuntimeError: bool value of Tensor with more than one value is ambiguous"

While when set requires_grad True for Data as well, then it works perfectly fine.  But when doing this, I get model gradients as None after backward

**To Reproduce**

```
import torch as th
import torch.nn.functional as F
import syft as sy
import random
import numpy as np

hook = sy.TorchHook(th)

bob=sy.VirtualWorker(hook, id="bob")
alice=sy.VirtualWorker(hook, id="alice")
sw=sy.VirtualWorker(hook, id="SecureWorker")

bob.clear_objects()
alice.clear_objects()
sw.clear_objects()

bob.add_workers([alice, sw])
alice.add_workers([bob, sw])
sw.add_workers([alice, bob])

x = th.tensor([[0,0], [0,1], [1,0], [1,1]]).to(th.float)
y = th.tensor([0,0,1,1]).to(th.float)

model=th.nn.Linear(2,1)

#print(list(model.parameters()))
enc_model = model.fix_precision().share(alice, bob, crypto_provider=sw, requires_grad=True)
optimizer = th.optim.SGD(enc_model.parameters(), lr=0.1)
optimizer = optimizer.fix_precision()

enc_data = x.fix_precision().share(alice, bob, crypto_provider=sw)
enc_target = y.fix_precision().share(alice, bob, crypto_provider=sw)

max_epochs=1
for i in range(max_epochs):
    optimizer.zero_grad()
    enc_pred = enc_model(enc_data).squeeze(1)
    l = (((enc_pred - enc_target) ** 2)).sum().refresh()
    l.backward()
    optimizer.step()
    l = l.get().float_precision()
    print(l.item())

model = enc_model.get().float_precision()
for params in model.parameters():
    print(params.grad)
print(enc_pred.get().float_precision())
```

Just run above code to reproduce error. Add ```requires_grad=True``` to enc_data and enc_target, to reproduce other error.

Please fix this.
Thanks.

**Comment by LaRiffle** [comment]
Hey, thanks for your feedback.
> While when set requires_grad True for Data as well, then it works perfectly fine. But when doing this, I get model gradients as None after backward

This is a bug related to `.squeeze(1)`. Remove this and you will get the gradient. I opened an Issue #2621 

> When we share the model and data to different virtual workers, then obviously it's the Model whose requires_grad should be True and data's requires_grad should be False

You're 100% right. However, if you know about PySyft, you know it relies chain of tensors like `Parameter>AutogradTensor>FixedPrecisionTensor>[AdditiveSharingTensor]...`. We currently hardly handle operating tensors with different chain structure, and in particular we don't support currently operating tensors with autograd and some who don't have them, that's why we asked `require_grad=True` for every tensor. But I'll report this as an issue and we'll try to have a better support. #2622

**Comment by sanvenDev** [comment]
Okay. Thanks.
