### ISSUE TITLE
Make PyTorch completely optional.

### ISSUE THREAD

**Issue by jvmncs** [OpenMined/PySyft#2632]
Currently, pytorch-dependent syft code is mostly separate from the core syft code (in that most core syft code does not need to import torch at all), but pytorch isn't yet truly optional.

This issue will be complete once the following have been completed and merged:
- [ ] `pip install syft` no longer installs the `torch` package as a dependency.
- [ ] `import syft` completes successfully without `torch` installed
    - This involves removing all current dependencies on torch outside of the `syft/frameworks/torch` subdirectory (potentially by making that code generic or moving it into that subdirectory when appropriate)
- [ ] `pytest .` does not fail when pytorch is not installed as a dependency (likely with heavy use of the `pytest.skipif(not dependency_check.torch_available)` decorator).

Once this work is completed, we can begin migrating torch-dependent syft code to [PySyft-PyTorch](https://github.com/OpenMined/PySyft-PyTorch).

**Comment by matthew-mcateer** [comment]
"truly optional"? I'm interpreting this as meaning building up the core syft code to be as independent of pytorch as possible, and setting up an optional pytorch backend much like `keras` does with `tensorflow` and `theano, right?

**Comment by jvmancuso** [comment]
Yes, more or less. There is some context missing from this issue, most of it can be found in [this RFC](https://github.com/OpenMined/rfcs/blob/master/20190808-modular-pysyft-frameworks.md), and more specifically [here](https://github.com/OpenMined/rfcs/blob/master/20190808-modular-pysyft-frameworks.md#packaging).

Worth noting that "building up the core syft code to be independent" is already complete.  What's left are the two of these checkboxes, and more specifically the latter because I'm about to fix the former.

**Comment by jvmancuso** [comment]
>Worth noting that "building up the core syft code to be independent" is already complete

This comment of mine is not true -- there was a bug hiding some extra dependencies, so I've updated the top-level comment to reflect the extra work.
