### ISSUE TITLE
Fix truncation in fixed precision and MPC

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2706]
**Describe the bug**
Truncation fails with n>2 workers when doing multiplication on additive shared tensor.

We would like to better understand situations when the sum of shares wraps around the field, to fix this.

### To reproduce

```python
import torch as th
import syft as sy

hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
charlie = sy.VirtualWorker(hook, id="charlie")
james = sy.VirtualWorker(hook, id="james")

torch = th
syft = sy
crypto_provider = james

args = (alice, bob, charlie)
kwargs = dict(crypto_provider=crypto_provider)

x = torch.ones(4, 1).fix_prec().share(*args, **kwargs)
y = torch.ones(4, 1).fix_prec().share(*args, **kwargs)

z = x * y
z.get().float_prec()
```

**Comment by LaRiffle** [comment]
@Yugandhartripathi I guess your PR significantly helps for this issue, but the problems is still there.
I've put an example to reproduce in the description

**Comment by aanurraj** [comment]
I will take this up :)

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
