### ISSUE TITLE
not able to install pysyft for pytorch version 1.3

### ISSUE THREAD

**Issue by somiljain7** [OpenMined/PySyft#2767]
![Screenshot (3)](https://user-images.githubusercontent.com/42209500/70046397-fc24f600-15eb-11ea-8f84-d7df9d69ffba.png)

**Comment by ChenghuiS** [comment]
I had the same problem and have solved it.

This problem seems only occur on Windows.

Reason: on windows, pip cannot find a version for torch==1.3,  but can find a version for torch==1.3.x (like torch 1.3.1). 
```powershell
(dl) PS C:\Users\Chenghui_S> pip install torch==1.3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting torch==1.3
ERROR: Could not find a version that satisfies the requirement torch==1.3 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3
(dl) PS C:\Users\Chenghui_S> pip install torch==1.3.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch==1.3.1 in c:\programdata\miniconda3\envs\dl\lib\site-packages (1.3.1)
Requirement already satisfied: numpy in c:\programdata\miniconda3\envs\dl\lib\site-packages (from torch==1.3.1) (1.17.4)
```

So if you change the requirement from 1.3 to 1.3.x (in your computer), you can solve this.

Details:
1. download source code
```powershell
git clone -b dev --single-branch https://github.com/openmined/PySyft.git
```
2. change the requirement file in path:     `./PySyft/pip-dep/requirements.txt`
![批注 2019-12-03 201433](https://user-images.githubusercontent.com/22197327/70050307-96476700-1609-11ea-95cc-066abfc8e728.png)
3. install
```powershell
cd PySyft
python setup.py install
```
4. in this step, if you occurs error about: `Microsoft Visual C++ 14.0 is required`, you can download Visual Studio 2019.  See: https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

**Comment by vvmnnnkv** [comment]
Installing pytorch with `conda install pytorch==1.3.0 -c pytorch` before syft worked for me on Win10.
(Note exact 1.3.0 version, not just 1.3)

**Comment by gmuraru** [comment]
@somiljain7 are you still having the issue?

**Comment by Naif18** [comment]
I tried most of the solution that I read but no one is useful 
this is the error
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3.1

**Comment by phenomenal-manish** [comment]
Getting the same error as @Naif18

**Comment by manishkadam007** [comment]
You can check this link: https://stackoverflow.com/questions/61850455/could-not-find-a-version-that-satisfies-the-requirement-torch-1-4-0-from-syft .

**Comment by Naif18** [comment]
> Getting the same error as @Naif18
I found the right solution that could solve this issue:
- Reinstall pytorch from here [https://pytorch.org/get-started/locally/#mac-package-manager](url)

- Make sure the **toch** version is 1.4.0 if it's not run the following command:
pip install syft -f https://download.pytorch.org/whl/torch_stable.html

- Now, you can download **syft** successfully:
pip install syft

to check the version of packages:
conda list
