### ISSUE TITLE
Translate our tutorials to Hindi

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2774]
At present, our tutorial notebook series is only available in English, but it would be very desirable for people to be able to learn PySyft in their native language, such as Hindi.

For this PR, copy the current notebooks and translate the inline text to Hindi, placing the notebooks in a "hindi" folder within the "tutorials" folder.

https://github.com/OpenMined/PySyft/tree/master/examples/tutorials

**Comment by Yugandhartripathi** [comment]
I am on it!

**Comment by kaustubh-seachange** [comment]
I can also contribute to this task

**Comment by Yugandhartripathi** [comment]
@kaustubh-seachange @darkmatter18 wanna split the work and get it done faster together?
if yes: I am using nbTranslate followed by proof reading then some manual editing and corrections.  What about you? Would love to know if there's a better way to do it.

**Comment by darkmatter18** [comment]
@Yugandhartripathi @kaustubh-seachange  Love to split the work. Please tell me which notebooks you guys want to work on?

**Comment by Yugandhartripathi** [comment]
Alright then I will handle work on Parts 11, 12, 12-bis, 13a, 13b, 13c

**Comment by darkmatter18** [comment]
As, i started from the beginning, I will go for 2,3,4,5,6. 1 already done

**Comment by kaustubh-seachange** [comment]
Which leaves me to take up the 7 to 10.

**Comment by raheja** [comment]
Hey everyone! I am on this task as well. If your are all ok, I can take up 5, 6, 13b and 13c. Work equally divided among all. What say?

**Comment by Yugandhartripathi** [comment]
@raheja The more the merrier. Let's get it done!

**Comment by darkmatter18** [comment]
@Yugandhartripathi can you please review my Pull request #2787

**Comment by raheja** [comment]
Hey guys, a few things to consider before we make pull requests -
(a) Since our work is divided among four, we all need to have a few set of rules that we stick to. For instance, 'name translations', like Bob or Alice if done in Part1, need to followed through till the end.
(b) Andrew has updated in the ticket before, regarding what all needs to be translated. Other than error messages and PySyft library imports, all other english terms should be translated. 
(c) In your notebooks, do not put yourself as 'translators'. We are editors since we are using a software for translation, and just overlooking edits if needed.

Would a sync up on our methods and progress be preferable to everyone?

**Comment by aeroaks** [comment]
Hi All, Count me in for the translation efforts! I would be happy to help!

**Comment by raheja** [comment]
Hey all, I have finished my assigned translations. As mentioned above, I am not putting my name under 'translator'. So 'anuvadak' is nbTranslate, while 'sampadak', or editor, is me. I believe we can also use, 'NbTranslate का उपयोग करके ... (your name) द्वारा अनुवादित'.  Let me know your thoughts.

Since my notebook numbers are 5, 6, 13b, 13c  do you all think we should proceed with uploading the tutorial 4, and the rest before I upload mine? Let me know.

In case others are not getting time to translate the tutorials, I can finish off the remaining ones as well. Again, let me know.  :)

For those who might come across the word 'predictions' in their tutorials, the default hindi translation is 'bhavishyavani',. I have used the term, ' पूर्वानुमान ' instead. That made more sense to me. 
So, gist  --- please let me know your suggestions.   :)

**Comment by Yugandhartripathi** [comment]
@raheja no need to wait for intermediate translations you can proceed to upload the ones you have completed.

As for translator name others have put their names in there I understand your views on it but I think it's more about taking responsibility for the translations which will be done better if there is a person's name on there plus the editor title is a bit ambiguous here as there are often various small changes and fixes in code and notebooks done by countless contributors all of them eligible for editor title but we can't have all the names up there some must work from the shadows and live on in Github commit history's hall of fame.

 ' पूर्वानुमान ' definitely makes more sense here.

As for the remaining notebooks I plan to complete my self assigned parts i.e. 11,12,12-bis,13a in a few days.

**Comment by kaustubh-seachange** [comment]
@Yugandhartripathi  @raheja I think some translated words to hindi have different meaning in a particular context and I think we can leave it upto 'Vivek' of contributor to come up with appropriate translated word. Just my thought on this :)

Also over a weekend i should be able to complete pending items 9, 10.

**Comment by kaustubh-seachange** [comment]
@Yugandhartripathi @raheja @darkmatter18  please review PR #2833

**Comment by raheja** [comment]
Hey guys!
@darkmatter18  @Yugandhartripathi @kaustubh-seachange 

We plan to release the hindi translations by next month, which leaves us a few days to finish all of them and review them too. Any heads-up on when they would be complete? In case it is not possible for some one to finish theirs, please do let the others know. Preferably by this weekend, so that they can be taken up by the rest of us.

Cheers!
Urvashi
