### ISSUE TITLE
Multi-Language Notebook Support in Tutorials

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2783]
We would like to have the ability to have one set of tutorial notebooks with multiple language options. Please modify our current jupyter notebooks to be able to support multiple languages inline using a technique such as https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/nbTranslate/README.html#compatibility

**Comment by refactormyself** [comment]
@iamtrask please can you clarify the task here. 

The nbTranslate extension has to be installed by the user. I tried it using Chrome and Firefox. I can view the tutorials several languages and switch between them.

Are we trying to generate a .pot file for each tutorial, so that .po file can be created as needed for each language per tutorial?

**Comment by seungjaeryanlee** [comment]
@iamtrask I see some issues dedicated to each language. ([German](https://github.com/OpenMined/PySyft/issues/2781), [Japanese](https://github.com/OpenMined/PySyft/issues/2780), [Chinese](https://github.com/OpenMined/PySyft/issues/2778)) Can I translate the notebooks to a different language without an issue? I would like to translate the tutorials to Korean.

Also, can the work be divided into multiple PRs? (ex. per notebook)

**Comment by seungjaeryanlee** [comment]
Never mind! #2782 answers all my question.
