### ISSUE TITLE
RuntimeError: invalid argument 8: lda should be at least max(1, 0), but have 0 at /pytorch/aten/src/TH/generic/THBlas.cpp:363

### ISSUE THREAD

**Issue by Madhura12gj** [OpenMined/PySyft#2861]
Runtime error when running:

` def train( ):
  opt = torch.optim.SGD(params=model.parameters(),lr=0.1)
  for epoch in range (20):
    model.train()
    print("Training started..")

    for x_data,y_data in datasets:

      model.send(x_data.location) 
      
      opt.zero_grad()
      
       #forwardpass
       #the model here is the linear regression model
      y_pred = model(x_data)

      #ComputeLoss
      loss=criterion(y_pred,y_data)

      #BackwardPass
      loss.backward()

      opt.step()

      model.get() #MIGHT HAVE AN ERROR, since .get() method is used only on pointers

      print(loss.get())`

**Error message:**

` PureFrameworkTensorFoundError             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/syft/frameworks/torch/tensors/interpreters/native.py in handle_func_command(cls, command)
    287             new_args, new_kwargs, new_type, args_type = hook_args.unwrap_args_from_function(
--> 288                 cmd, args, kwargs, return_args_type=True
    289             )

25 frames
PureFrameworkTensorFoundError: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/syft/frameworks/torch/tensors/interpreters/native.py in handle_func_command(cls, command)
    320             # in the execute_command function
    321             if isinstance(args, tuple):
--> 322                 response = eval(cmd)(*args, **kwargs)
    323             else:
    324                 response = eval(cmd)(args, **kwargs)

RuntimeError: invalid argument 8: lda should be at least max(1, 0), but have 0 at /pytorch/aten/src/TH/generic/THBlas.cpp:363`

**Expected behavior**
I expect the error message to be clearer and easily understandable. I find it very difficult to understand the error.

**Comment by karlhigley** [comment]
I think this has to do with calling `get` on the model inside the loop. The typical semantics of `get` in Syft move the object from the remote worker to the location where `get` is executed, [destroying the remote object in the process](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/generic/pointers/object_pointer.py#L228-L235).

Not 100% sure, but I think the `PureFrameworkTensorFoundError` is telling you that Syft expected to receive a pointer to a remote tensor but got a local Torch tensor instead, and the second error is coming from deep with PyTorch's linear algebra library, where it's trying to do tensor math but not getting valid parameters (maybe as a result of the first issue.) I can't quite trace all the way through the code to verify that's exactly what's happening, but hopefully it's enough to point in a useful direction.

What happens if you remove `model.get()` or move it after the loop?

**Comment by Madhura12gj** [comment]
> Not 100% sure, but I think the `PureFrameworkTensorFoundError` is telling you that Syft expected to receive a pointer to a remote tensor but got a local Torch tensor instead, and the second error is coming from deep with PyTorch's linear algebra library, where it's trying to do tensor math but not getting valid parameters (maybe as a result of the first issue.) I can't quite trace all the way through the code to verify that's exactly what's happening, but hopefully it's enough to point in a useful direction.

Yes! you were right, moving the model.get() outside loop helped Thanks! But I now face a dimension error saying, "Dimension out of range (expected to be in range of [-1, 0], but got 1)"

**Comment by karlhigley** [comment]
Hmm, not sure I've helped much yet. At least we know it's the `model.get()` where the problem occurs, but I think you already knew that.

**Comment by tushar-semwal** [comment]
Check this issue if the RunTime error persists. https://github.com/pytorch/pytorch/issues/20006
This error is related to PyTorch.
