### ISSUE TITLE
Modify Wrapper API Based On Chain

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2957]
**Is your feature request related to a problem? Please describe.**
At present, whenever we create a new tensor type, we add corresponding functionality to syft/frameworks/torch/tensor/interpretor/native.py. For example, when we created the PaillierTensor, we created a .encrypt() method which gets added to every torch tensor no matter what, even when it can't be encrypted (even when it is _already_ encrypted).

It would be better if wrapper tensors only had methods which applied to their underlying tensor chain, and I think this is possible.

**Describe the solution you'd like**
I would like for the wrapper around a tensor to dynamically expose the methods which apply to it, or at least have good error messages when we use a method at the wrong time.

**Describe alternatives you've considered**
Alternatively, we could port all our tensors to use PyTorch's new custom tensor functionality (this is probably better in the long run, but it's a bigger project).

**Comment by karlhigley** [comment]
Though it need not supersede this issue, I'm in favor of starting research/prototyping/etc on that alternative sooner rather than later. The longer we put it off, the more work we're going to pour into workarounds in the mean time.

I don't fully understand how porting to custom PyTorch tensors would resolve this issue though. Is it because that would allow us to stop using wrapper tensors?

**Comment by LaRiffle** [comment]
Bother solutions look good to me!
Could you point at reading material for "PyTorch's new custom tensor functionality" ? thanks :)

**Comment by karlhigley** [comment]
@LaRiffle I had to look in the docs on master to [find it](https://pytorch.org/docs/master/notes/extending.html#extending-torch-with-a-tensor-like-type). Looks pretty handy, but obviously a big rework to adopt it.
