### ISSUE TITLE
Requirements need updates

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3330]
**Describe the bug**
ERROR: syft 0.2.4 has requirement syft-proto~=0.2.5.a1, but you'll have syft-proto 0.2.9a2 which is incompatible
ERROR: syft 0.2.4 has requirement tornado==4.5.3, but you'll have tornado 6.0.4 which is incompatible.

**To Reproduce**
pip install syft-proto --upgrade

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by karlhigley** [comment]
`pip install --upgrade syft-proto` will force an upgrade to the newest available version of `syft-proto`, which is indeed incompatible with `syft 0.2.4`.

Fixes for the tornado version issue were merged in #3196, #3204, and #3288. (It may require manually downgrading your tornado version, because the previous dependency specification was overly optimistic about compatibility.)
