### ISSUE TITLE
`test_instantiate_tfe_layer` is flaky

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3344]
**Describe the bug**
This test semi-regularly fails 

**To Reproduce**
Run the test (or full suite) until it fails.

**Expected behavior**
The test should reliably pass.

**Screenshots**
```
        # compares results and raises error if not equal up to 0.001
>       np.testing.assert_allclose(actual, expected, rtol=0.001)
E       AssertionError: 
E       Not equal to tolerance rtol=0.001, atol=0
E       
E       Mismatched elements: 4 / 20 (20%)
E       Max absolute difference: 0.00031287
E       Max relative difference: 0.00110612
E        x: array([[-0.163999, -1.074379, -1.394909, -0.963268,  0.888889],
E              [-0.163999, -1.074379, -1.394909, -0.963268,  0.888889],
E              [-0.163999, -1.074379, -1.394909, -0.963268,  0.888889],
E              [-0.163999, -1.074379, -1.394909, -0.963268,  0.888889]])
E        y: array([[-0.164181, -1.074468, -1.395135, -0.9634  ,  0.889202],
E              [-0.164181, -1.074468, -1.395135, -0.9634  ,  0.889202],
E              [-0.164181, -1.074468, -1.395135, -0.9634  ,  0.889202],...
```

**Additional context**
This started being an issue when the order of the test suite was randomized (specifically to shake out flaky tests like this.)

**Comment by jvmncs** [comment]
There are two potential issues here:
1. Randomized functions in tests should be seeded, since integration tests should be deterministic. By randomizing the order of tests, the seed that these tolerance values are tuned against might be getting reset.
2. The rtol value here is working against the test definition, which is what makes this test dependent on seed.

To explain 2 a bit more:The loss of precision from TFE's fixed point representation truncating floating points is relatively worse for values closer to 0, and sampling kernel_initializer from a standard normal means we have a high likelihood of sampling numbers near 0. Relative error between the expected and actual value of the kernel will thus increase for numbers near 0 (whereas absolute error should be better).

If you want to randomize testing order, I'd double check that you're setting seeds after sampling the testcase order (so that each test can still be deterministic). I'd additionally either change the kernel_initializer to a distribution that doesn't have an expected value at 0 (normal -> uniform), or switch from rtol to atol (this is less satisfying but should at least make the test less susceptible to precision errors).

**Comment by karlhigley** [comment]
The issue that prompted randomizing the test case order was that changes to the directory structure (without code changes) could cause test failures, since the tests are run in alphabetical order and randomized functions in the tests are inconsistently (re-)seeded.

**Comment by karlhigley** [comment]
(For anyone picking up this issue, the test randomization is performed with [`pytest-randomly`](https://github.com/pytest-dev/pytest-randomly).)

**Comment by jvmncs** [comment]
>randomized functions in the tests are inconsistently (re-)seeded

Seems like a great use case for [pytest fixtures](https://docs.pytest.org/en/latest/fixture.html)

**Comment by karlhigley** [comment]
Not sure I follow. Are you suggesting using fixtures to set random seeds?

**Comment by jvmncs** [comment]
Yes, assuming there's a reason that no global seed is used.

**Comment by jvmncs** [comment]
>Setting fixed random seeds at the beginning of a test run doesn't solve the issue though, because the order of the tests is not fixed, so the numbers generated for each individual test may vary.

I see, I misunderstood. Dynamically setting the seed based on timestamp is not what I'd consider "fixed seed" because it doesn't allow for exact reproducibility of a test run across time & machines. But at least the problem is clear now, we need same numbers across runs for this issue to be fixed

**Comment by karlhigley** [comment]
It does allow for reproducibility, because each test run prints out the random seed at the beginning and you can pass it back in with a flag.

IMO, we need tests that are resilient to receiving different numbers, because the tests are already not guaranteed to run in the same order on every run (due to package path changing refactors.) I'd much rather intentionally deal with the problem of tests that flake (by randomizing their order and fixing issues) than have unrelated tests fail unexpectedly while refactoring due to order dependence of the test suite.

**Comment by karlhigley** [comment]
Anyway, #3358 adjusts the thresholds to make this test pass reliably, so this game of whack-a-mole has shifted to other parts of the code base.
