### ISSUE TITLE
Reduce complexity of ```create_sandbox```

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3430]
Split the code from ```create_sandbox``` into two separate functions and remove the ```noqa: C901```.

**Describe alternatives you've considered**
Simplify the function such that no split is required.

**Additional context**
Code quality:
```
2020-04-29T13:13:32.5968940Z ./syft/sandbox.py:12:1: C901 'create_sandbox' is too complex (26)
2020-04-29T13:13:32.5969257Z def create_sandbox(gbs, verbose=True, download_data=True):
2020-04-29T13:13:32.5969524Z ^
```

**Comment by Nike682631** [comment]
Hey, can i resolve this issue ?

**Comment by ShivaBadaja** [comment]
@gmuraru Can i work on this?

**Comment by gmuraru** [comment]
Hey @Nike682631. Sorry for the late reply. Sure, you can work on it!

**Comment by u-prime** [comment]
Can I take this issue?

**Comment by gmuraru** [comment]
Sure!

**Comment by hemameh** [comment]
Can you please provide more info on how you want to split to be done ?

**Comment by hemameh** [comment]
Can I take this issue ?

**Comment by gmuraru** [comment]
Sure! Sorry :(, I do not know how I missed this notification. You can also ping me on the slack channel.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
