### ISSUE TITLE
MPC on private tensor

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#3537]
**Description of the feature**
Private Tensors (PTs) provide a great functionality managing the users who can `get()` a tensor (see https://blog.openmined.org/what-is-pygrid-demo/)

PySyft provides Additive Sharing Tensors (ASTs) for working with mpc, however this is not implemented for PTs. See the following example:

```
import syft as sy
import torch as th

hook = sy.TorchHook(th)

# workers
alice = sy.VirtualWorker(hook=hook, id="alice")
bob = sy.VirtualWorker(hook=hook, id="bob")

# data alice and bob
## private
data_alice = th.tensor([2]).private_tensor(allowed_users=("alice",)).tag("data_alice_private")
ptr_alice = data_alice.send(alice, user="alice")
#
data_bob = th.tensor([3]).private_tensor(allowed_users=("bob",)).tag("data_bob_private")
ptr_bob = data_bob.send(bob, user="bob")

## AST
ptr_ptr_alice_private = ptr_alice.share(alice,bob)  # ptr AST1
ptr_ptr_bob_private= ptr_bob.share(alice,bob)  # ptr AST2

## Math operations
z1 = ptr_ptr_alice_private.get() #  AST1
z2 = ptr_ptr_bob_private.get() # AST2
z = z1 +z2 # AST1 + AST2
z = z.get()  # 5
```

This example throws the following exception:

```
  File "/home/bda/Documents/mpc/PySyft/syft/frameworks/torch/tensors/interpreters/native.py", line 901, in share
    shared_tensor = chain.share(
AttributeError: 'PrivateTensor' object has no attribute 'share'
```

Notice that if we work with native_tensors the snippet of code would work.

**Describe the solution you'd like**
The solution would be to implement MPC in Private Tensor  (like precision_tensor or similar)

**Comment by Avi-000-Avi** [comment]
Can I take up this problem?

**Comment by QuantumA** [comment]
analyzing it :)

**Comment by jmaunon** [comment]
> analyzing it :)

Nice! I have been analyzing as well! One you have some conclusions, we could use this issue in order to exchange our impressions

**Comment by iamtrask** [comment]
@Avi-000-Avi all you - this is a great first issue if its your first.

**Comment by karlhigley** [comment]
There are (at least) two possible approaches here:
* Add `share` and other MPC methods to `PrivateTensor` (easier and will totally work for now)
* Consolidate the tensor privacy and permissions functionality from `PrivateTensor` into one of the base classes for tensors (probably `AbstractTensor`), so that all tensors have both permissioning and MPC (harder but more robust in the long term)
Either way is fine for resolving this issue. If we end up doing the first one for now, then we can create a separate issue to do the second refactor later.

**Comment by Avi-000-Avi** [comment]
> @Avi-000-Avi all you - this is a great first issue if its your first.

Yeah working on it🙃

**Comment by jmaunon** [comment]
> There are (at least) two possible approaches here:
> 
> * Add `share` and other MPC methods to `PrivateTensor` (easier and will totally work for now)
> * Consolidate the tensor privacy and permissions functionality from `PrivateTensor` into one of the base classes for tensors (probably `AbstractTensor`), so that all tensors have both permissioning and MPC (harder but more robust in the long term)
> 
> Either way is fine for resolving this issue. If we end up doing the first one for now, then we can create a separate issue to do the second refactor later.

I agree with these two approaches. What I have been thinking is what happens with the permissions of the result, I mean if we are capable of sum 2 Private Tensor (via MPC), where each tensor has different permission, the result would include both permissions? Is an open comment :)

**Comment by karlhigley** [comment]
Since the result may reveal information about the inputs, it should default to having the most restrictive permissions found among the inputs. There may be certain cases/operations where it's safe to reveal the output, but we should err on the side of privacy by default.

**Comment by jmaunon** [comment]
Hi, any update?

**Comment by marload** [comment]
If this work is not in progress, I would like to do it.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
