### ISSUE TITLE
Add All Methods to PySyft's Autograd System

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3550]
**Is your feature request related to a problem? Please describe.**
In order to backpropagate on top of our custom tensor types, we've had to build our own autograd. All the mechanics are in this file: https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/tensors/interpreters/autograd.py

However, while the autograd works, it doesn't have very many methods - and we need it to work for all methods and functions supported by PyTorch (https://pytorch.org/docs/stable/tensors.html)

**Describe the solution you'd like**
Add all the methods to autograd system and test them.

**Describe alternatives you've considered**
PyTorch has a markdown file with all functions and their supported backprop logic - which we could use to code generate our autograd. Talk to me if you're interested in this.

**Additional context**
This is a blocker for important work @vvmnnnkv and others are working on.

**Comment by punitvara** [comment]
Interested @iamtrask

**Comment by cereallarceny** [comment]
@vvmnnnkv

**Comment by vvmnnnkv** [comment]
This issue looks like more generic version of https://github.com/OpenMined/PySyft/issues/3509?

Note that #3509 was postponed because there's no clearance if Autograd tensor should be used for autograd tracing in Plans. Autograd tensor is only used together with FixedPrecision and AdditiveSharing tensors and at least wasn't intended for tracing.
