### ISSUE TITLE
How to implement the federated learning using several computers?

### ISSUE THREAD

**Issue by NeuZhangQiang** [OpenMined/PySyft#3793]
## Question
I am still confused about how to implement the federated learning using several computers after run the example PySyft-master/examples/tutorials/advanced/websockets_mnist. 

## Further Information
The example of websockets_mnist create servers and clients. However, I don't understand the role of servers in this project, because all data is loaded and the model average is performed in the run_websocket_client.py. The run_websocket_server.py just create 3 servers, thus I don't understand the importance of WebsocketServerWorker. In my understand, each clients should has a part of data rather than the whole data; the server should collect all models from clients and average it. This example make me confused. 

The most important thing that I want to know is: how the server and client can communicate? How can a server let the client (another computer) start training? How can a server get the model from the client (another computer)? 

Can PySyft provide an example for such question? Any suggestion is appreciated!

**Comment by chenwanqq** [comment]
First of all, the websocketServerWorker class is totally broken in present version(0.2.6), since those developers removed train_config and cause too many bug to fix. So if you want to imply multi-machined FL, an easy way is to use PySyft-0.2.5.
Base on PySyft-0.2.5, here is my understanding. Each client run a websocketServerWorker("Server" means hold the data), and server run a websocketclient to remote access the correspond websocketserverworker using the url that provided.
Each turn, server send the complied compute graph of the model(complied by torch.jit.trace) and its weight to client, client do the training and send back to the server. Finally server uses FedAvg algorithm to combine them.
the most accurate tutorial you should read is https://github.com/OpenMined/PySyft/tree/v0.2.5/examples/tutorials/advanced/websockets_mnist_parallel.
