### ISSUE TITLE
FALCON: Basic Operations

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3852]
## Feature Description
To build Falcon protocol we will need to build some basic building blocks:

- [X] Select Shares i.e. given two shares(x,y) and a bit (b mod 2): select x if b== 0 ; else select y
- [X] XOR a secret with public bit
- [X] Evaluating [(-1)^B * x ]^m

## Additional Context

[FALCON papaer](https://arxiv.org/pdf/2004.02229v1.pdf)

**Comment by IanQS** [comment]
Hey @abogaziah ! 

Sorry, but would it be possible to add a checkbox in front of each of those tickets so that we can see which ones are in progress or finished without needing to open each ticket? Sorry, it's been a while since I've used Github to track epics and milestones so I'm a little confused

**Comment by abogaziah** [comment]
Hi @IanQS ! I updated the epic, we have split it into 2 milestones where you can know what's done and what's not:  
https://github.com/OpenMined/PySyft/milestone/15
https://github.com/OpenMined/PySyft/milestone/14
Falcon milestone isn't complete yet

**Comment by gmuraru** [comment]
Solved
