### ISSUE TITLE
AutogradTensor.backward() in sy.Plan does not propagate to the entire NN model

### ISSUE THREAD

**Issue by santteegt** [OpenMined/PySyft#3980]
## Description

I'm trying to use the example code from [Part 01 - Create Plan.ipynb](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/model-centric-fl/Part%2001%20-%20Create%20Plan.ipynb) to create a Plan for an LSTM model that I built using a modular approach. However, when executing the `loss.backward()` the gradient error does not propagate back to all layers (& model parameters) in the model besides the ones defined in the last subclass/module

## How to Reproduce
1. Here's my LSTM implementation https://gist.github.com/santteegt/55ec836b00493ded4479c1cefa9f5c8a
2. Execute using a dev PySyft environment
3. You'll get an error `TypeError: mul(): argument 'other' (position 1) must be Tensor, not NoneType` in the `naive_sgd` function due to a `param.grad` is None

## Expected Behavior
All model parameters should have a grad != None

**Comment by tvmsouza** [comment]
I have the same problem but with a convolutional network, mainly with a Conv2d layer. I think that the problem is related to issue #3509 and this one  #3550. I want to contribute for solve the problem and make .grad of this layer different from None. I tried use the Conv2d from syft/frameworks/torch/nn/conv. But I'm still without success, the same occurs when a modified the autograd.py to support conv2d on backward pass. Based on the related issues I think, if available, that @iamtrask @karlhigley  and @vvmnnnkv can give us a start guide or tips to make these layers work in this example. I really want to contribute guys :+1: .

**Comment by LimingFang** [comment]
the same question
