### ISSUE TITLE
Benchmark Normal Inference vs SMPC Inference - using the approx methods

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4002]
## What?
Benchmark on how long it takes to do an inference using a pre-trained model: SMPC vs Normal setup.

As the model, we can use a simple convolutional network and as the dataset, we can use MNIST.
A good starting point can be the tutorials.

The final output should be a graph or graphs (png images) where:
* X-axis - the used precision for the ```FPT```
* Y-axis - the time inference

We can have multiple lines, each one representing an approximation method.

Normal inference time vs SMPC inference time + difference in accuracy

See the [Epic](https://github.com/OpenMined/PySyft/issues/3997) to check for more details.

**Comment by kamathhrishi** [comment]
I could take it up :)

**Comment by gmuraru** [comment]
Hey. There is Sergiu Craioveanu that is working on this issue.

**Comment by gmuraru** [comment]
This issue is up for take :D

**Comment by aanurraj** [comment]
I will take this up :)

**Comment by just-a-nybble** [comment]
Is this still needing to be completed? If so I would love to work on it for a class project this semester!

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
