### ISSUE TITLE
Removing the hosted data or model

### ISSUE THREAD

**Issue by cheneeheng** [OpenMined/PySyft#4016]
## Question
How to remove the hosted data/model or the trained checkpoint that is in the grid for FL?

## Further Information
I set-up my FL code using the tutorials provided. The code works and it runs until the end. But when i want to rerun it, the training doesnt start because the grid thinks that the training has completed (due to previous run). What I am doing now to overcome this is to restart the grid server everytime I want to run the code. Is there a way to delete the data/model/checkpoint in the grid? I couldn't find it anywhere. Although this is not a problem during deployment, but it would be nice to have when doing experiments. Thanks !

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Ubuntu
 - OS Version: 18.04LTS
 - Language Version: Python 3.6
 - Package Manager Version: Docker

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
