### ISSUE TITLE
torch.jit.scrip model call error in hook

### ISSUE THREAD

**Issue by wry2020** [OpenMined/PySyft#4034]
## Question
**When after running hook = syft.TorchHook(torch), then call lstm_crf model with torch.jit.script format, the following problems appear.**

## Further Information
When I use pysyft0.2.5 to run the asynchronous lstm_crf network model, there is no problem when torch.jit.script is instantiated before hook = syft.TorchHook(torch)【right: init_model() is before hook = syft.TorchHook(torch)】, but after running hook = syft.TorchHook(torch), then torch.jit.script the network, the following problems appear【error: init_model() is after before hook = syft.TorchHook(torch)】. Does anyone know what caused it?. Thanks very much!

## Screenshots
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/60022880/90480998-a71e1580-e163-11ea-8ea2-6a8d07c32a0f.png">

call method:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/60022880/90481323-27dd1180-e164-11ea-967b-ab367b6c6cd0.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/60022880/90481291-1a278c00-e164-11ea-9501-c9006f306a77.png">

## System Information
 - OS: Mac
 - OS Version: 10.15.4
 - Language Version: Python 3.7, pysyft 0.2.5

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
