### ISSUE TITLE
Is there any function with similar the syft.TrainConfig function in the subsequent PySyft version?

### ISSUE THREAD

**Issue by XiaotianJia** [OpenMined/PySyft#4040]
I found that `syft.TrainConfig` function  mentioned in issue #4028 was removed after version 0.2.5. Is there any function with similar it in the later PySyft version?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
