### ISSUE TITLE
AST division based on reciprocal

### ISSUE THREAD

**Issue by marload** [OpenMined/PySyft#4053]
## Description

The division of the `securenn` is very slow. We can implement `A / B` using `A * B^-1`. This is expected to be much faster than the division of `securenn`.

## Are you interested in working on this improvement yourself?
- I'm interested in implementing this, but it's hard right now.

## Additional Context

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
