### ISSUE TITLE
Is there any API for compressing model updates(gradients or model difference)?

### ISSUE THREAD

**Issue by Ethanwl** [OpenMined/PySyft#4466]
If the differences were sparse, they'd be smaller. They often won't be though.

Gradient sparsification is a thing; maybe model delta sparsification could be too?

_Originally posted by @karlhigley in https://github.com/OpenMined/PySyft/issues/2934#issuecomment-576350240_

Is there any API for compressing model delta using sparsification(topK or randomK) or quantization now?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.

**Comment by amitport** [comment]
@cereallarceny sorry to repeat the question above, but does such an API exists (in 0.3.x and later). If not could this be reopned?

thanks
