### ISSUE TITLE
Duplicated method name in base.py

### ISSUE THREAD

**Issue by gkaissis** [OpenMined/PySyft#4477]
`syft/workers/base.py` contains two identically named `register_obj` methods:

https://github.com/OpenMined/PySyft/blob/99190dfa85d86b1d6542a7ee0454b2758c289605/syft/workers/base.py#L189

and 

https://github.com/OpenMined/PySyft/blob/99190dfa85d86b1d6542a7ee0454b2758c289605/syft/workers/base.py#L553

In best python tradition, only the latter one actually gets called, but we should fix that.

**Comment by varun68** [comment]
@gkaissis ..I would like to give this a shot..how would you like me to approach this bug?

**Comment by gkaissis** [comment]
Could you please see to the failing tests and perhaps @cereallarceny or @gmuraru have a look? This was a subject of discussion recently owing to the issues we had with websocket training

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
