### ISSUE TITLE
Remote should return a wrap of the pointer tensor

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4483]
## Description
We have a way to specify what functions are allowed to run remotely by using the decorator ```allow_command``` and after this, if we want to run that function on a remote worker, we can use ```remote```.

The ```remote``` function runs the command on a remote worker and returns a ```PointerTensor``` - the problem is that we should be consistent and the ```remote``` function should also return a ```wrapper``` of the ```PointerTensor```.

**Comment by mateidanut** [comment]
I could do it. Is it sufficient to just call the wrap() method on the returned PointerTensor?

**Comment by gmuraru** [comment]
Hey. It might not be that easy. You can start doing that and then check out what/how breaks.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
