### ISSUE TITLE
Remove duplication of Benchmark

### ISSUE THREAD

**Issue by marload** [OpenMined/PySyft#4486]
## Description

Duplicate of code contained in `benchmarks/frameworks/torch/mpc/scripts` must be removed.

The `benchmark_X.py` included a very similar shape. Create reusable Benchmark modules using function extraction.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
