### ISSUE TITLE
Add datasets to sandbox

### ISSUE THREAD

**Issue by u-prime** [OpenMined/PySyft#4517]
### **Description**
We want to extend the datasets of the Sandbox.
Currently the Sandbox download datasets from Sklearn, and the goal of this project is add additional datasets from Tensorflow.

We added the following datasets: fashion_mnist and Cifar10.

We the function: load_tf to load data from TensorFlow datasets.
In addition, since the above datasets are large and might cause problem on machines with not enough memory, we limited the number of records to be distributed (see num_of_records = 10000 in the load_tf function)

**Comment by u-prime** [comment]
I would like to work on this issue (as part of my boot camp project)

**Comment by Prtfw** [comment]
all yours @u-prime

**Comment by LaRiffle** [comment]
@u-prime any updates on this?

**Comment by u-prime** [comment]
Have some difficulties with the Lint step. Still working on this

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
