### ISSUE TITLE
Upgrade to PyTorch 1.6

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4556]
Follow up from https://github.com/OpenMined/PySyft/issues/3395
We are 0.2 versions behind

**Comment by Nilanshrajput** [comment]
crypten requires torch1.4 that will be a conflicting dependency

**Comment by gmuraru** [comment]
Could you try with the latest ```crypten``` master?

**Comment by Nilanshrajput** [comment]
okay i will check

**Comment by Nilanshrajput** [comment]
the master is on torch1.5 maybe we can bump to 1.5 first

**Comment by gmuraru** [comment]
Sounds like a plan. What do you think, @LaRiffle ?

**Comment by LaRiffle** [comment]
Opacus is on torch 1.6, and upgrades are always a bit annoyins, so I would say let's update as high as possible!

**Comment by wlnancy** [comment]
Hi, I have used torch 1.6,but when I use pip install opacus, it occurred error that:
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from opacus) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0 (from opacus)
I want to know how can I solve the problem?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
