### ISSUE TITLE
async training using Web sockets

### ISSUE THREAD

**Issue by okazaki0** [OpenMined/PySyft#4574]
Hello

Are there any way to train federated model in async way in the new version of PySyft? Something like trainconfig

**Comment by NeuZhangQiang** [comment]
The trainconfig seed to be removed in pysyft 0.2.6. I am not sure whether there is a replace method in pysyft 0.2.9.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
