### ISSUE TITLE
Protobuf serialization mode seems broken

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4585]
## Description
Have any of you used the protobuf serialization mode instead of the msgpack one?
I know we have one, but I switch to this mode by doing in `syft/serde/serde.py`
```
from syft.serde.msgpack import serialize as msgpack_serialize
from syft.serde.msgpack import deserialize as msgpack_deserialize
```
-> 
```
from syft.serde.protobuf import serialize as msgpack_serialize
from syft.serde.protobuf import deserialize as msgpack_deserialize
```

## How to Reproduce
I have tons of weird errors on the simple example:
```
message = th.tensor([[1., 2], [3, 4]])
message.send(alice).get()
```

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
