### ISSUE TITLE
ABY: Bit injection

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4590]
## Feature Description
Implement the bit injection algorithm described in [here](https://eprint.iacr.org/2018/403.pdf)
**EDIT**: We can defer this to later since the local party ("me") is the one that orchestrates all the computation and it plays a crypto provider kind of role.

## Is your feature request related to a problem?
The Falcon protocol requires the bit injection algorithm

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
