### ISSUE TITLE
Replace copy().get() with new get_copy parameter as get(get_copy=True)

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/PySyft#4634]
## What?
Replace copy().get() with new get_copy parameter in get() method

## Why?
The get_copy param lets you get a PySyft object without destroying the remote object, 
copy().get() was used as a hack to maintain a copy of PySysft object remotely after as get() destroys original object at remote location
## Breakdown
Just replace where `copy().get()` is used with `get(get_copy=True)`.

## Additional Context
None

**Comment by Bhuvan-21** [comment]
@Nilanshrajput  Can I work on this???

**Comment by Nilanshrajput** [comment]
@Bhuvan-21  go for it!! 
replace from every place in tutorials also.

**Comment by Bhuvan-21** [comment]
Okay, will start doing it.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
