### ISSUE TITLE
The program is getting slower and slower.

### ISSUE THREAD

**Issue by Ethanwl** [OpenMined/PySyft#4641]
## Further Information
For example, it takes 4 minutes in the first epoch, but in the 50th epoch it will take 8 minutes and in the 90th epoch it will take 13 minutes. Is there any suggestion to solve or find out the problem?

**Comment by LaRiffle** [comment]
Hey, on which code demo?
what does your computer metrics say? (RAM, cpu, etc?)
You probably have a RAM issue?

**Comment by Ethanwl** [comment]
It's not the demo in Pysyft example. It's my own codes and I write my own dataloader and training process. I train AlexNet in Cifar10 with 10 workers, but with other model and dataset there are also similar situation. Computer metrics: GPU: 2080Ti,  CPU: 16  Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz, RAM: 32GB.
Is there any suggestion to solve or find out the problem in my codes?

**Comment by LaRiffle** [comment]
Ah ok! 
Have you monitored memory usage to check if the RAM gets filled? We had in the past issues with memory leakage, it might be linked maybe

**Comment by Ethanwl** [comment]
Thank you for your help. My current Pysyft is 0.2.8 and 0.2.7(in two different computers). I run the codes in examples/tutorials/Part 06 for 100 epoch. There is no phenomenon that the epoch time keeps increasing(about 100s one epoch). Probably, there are some bugs in my own codes. I'll try to figure out it.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
