### ISSUE TITLE
How can secure model weight aggregation be done if we are connected to the secure worker via DataCentricFLClient?

### ISSUE THREAD

**Issue by sug4ndh** [OpenMined/PySyft#4672]
## Question
How can secure model weight aggregation be done if we are connected to the secure worker via DataCentricFLClient?

## Further Information
When doing the federated learning with trusted aggregator and when we are connected to the secure worker via DataCentricFLClient, how can one get the model weights after sending it to the secure worker? I get an error `AttributeError: 'DataCentricFLClient' object has no attribute 'parameters'`

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
