### ISSUE TITLE
how to appoint a remote local_worker when initializing hook

### ISSUE THREAD

**Issue by Doodlera** [OpenMined/PySyft#4753]
## Question
**Describe your question in ONE SENTENCE.**
how to appoint a remote local_worker when initializing hook
## Further Information
I find the description in class TorchHook(FrameworkHook) that 
"
local_worker: An optional BaseWorker instance that lets you provide a
local worker as a parameter which TorchHook will assume to be the
worker owned by the local machine. If you leave it empty,
TorchClient will automatically initialize a
:class:`.workers.VirtualWorker` under the assumption you're looking
 to do local experimentation or development.
"
I wonder whether could I appoint a local_worker object owned by remote machine when initializing hook.If the answer is yes,could you provide a demo?Thanks!!!

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
