### ISSUE TITLE
is there any methods for make local_worker not None when hook initiallized?

### ISSUE THREAD

**Issue by Doodlera** [OpenMined/PySyft#4754]
## Question
is there any methods for make local_worker not None when hook initiallized?

## Further Information

For example,
`
hook=sy.TorchHook(torch=torch,local_worker=None)
bob=sy.VirtualWorker(hook,id='bob')
`
All the worker based on class BaseWorker which needs hook,while hook needs local_worker initiallized.So,is there any methods for make local_worker not None when hook initiallized?
Thanks!!!!!!

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
