### ISSUE TITLE
Test GC on In-place Operators

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4764]
## Description
There are scenarios where GC might have issues with inplace_ tensor operations if the original pointer is cleaned up and the returned pointer after the mutation still points to the same torch memory. We should consider the different possibilities and write tests to evaluate the behaviour.

## Definition of Done
Tests prove this is either not a problem or that it is and we can discuss a possible solution.

**Comment by gmuraru** [comment]
Looked into this issue!

Run the following code:
```
alice = sy.VirtualMachine(name="alice")
alice_client = alice.get_client()
    
x_ptr = x.send(alice_client)
print(alice.store)
   
x_ptr2 = x_ptr.transpose(0, 1)
print(alice.store)
```
How the store looks:
1.
```
{<UID:0ba289de-72a8-415f-ad5f-fa322e104367>: <Storable:tensor([[1, 2, 3],    [4, 5, 6]])>}
``` <--- makes sense to be only one object since we sent one tensor
2.
```
{<UID:0ba289de-72a8-415f-ad5f-fa322e104367>: <Storable:tensor([[1, 2, 3],    [4, 5, 6]])>, <UID:0d01b581-fcde-46ff-b0de-e72cc161d6d6>: <Storable:tensor([[1, 4],    [2, 5],    [3, 6]])>}
``` <--- makes sense to be 2 objects since we called ```transponse``` on the tensor (and one is the transpose of the other)

With inplace methods/ops:
```
alice = sy.VirtualMachine(name="alice")
alice_client = alice.get_client()
        
x = th.tensor([[1,2,3], [4,5,6]])
x_ptr = x.send(alice_client)
print(alice.store)

x_ptr2 = x_ptr.transpose_(0, 1)
print(alice.store)
```
How the store looks:
1. ```{<UID:dbf20faa-d36e-446d-87cf-39b2d09368bd>: <Storable:tensor([[1, 2, 3],    [4, 5, 6]])>}```
2. ```{<UID:dbf20faa-d36e-446d-87cf-39b2d09368bd>: <Storable:tensor([[1, 4],    [2, 5],    [3, 6]])>, <UID:d9acfb0f-b215-4068-b32c-90142d68453a>: <Storable:tensor([[1, 4],    [2, 5],    [3, 6]])>}``` <-- since we used ```transpose_``` (does the inplace transpose + returns the same transposed tensor -- in our case pointer to tensor)

^^^ This might be an acceptable behavior depending on what we want.
1. ```transpose_``` creates another tensor with how the data should look after transposing + changes the underlying data for the value we called ```transpose``` on.

If a user calls ```x_ptr2.get()``` it would get one value and the value pointed by ```x_ptr``` still remains in the store.

Other behaviors might be:
1. Return a **new pointer** which points **to the same data** in the store:
  - calling get on a pointer would fetch and delete that data, the other pointer remains invalidated (a user calling get on it would get an exception because there is no data on the store).
   - deleting the **new** or **original** pointer would send a delete message to the store which would delete the underlying data -- the other pointer would point to invalid data.

2. Return the **same pointer** as the pointer we called the inplace operation on (we do not create a copy on the data on the store side)
- We would basically have *x_ptr2* and *x_ptr* but they are the same object (```id(x_ptr2) == id(x_ptr)```)
- The same downside is - doing *x_ptr.get()* or *x_ptr2.get()* would make the other point to invalid data (data that was removed)

What we are doing now I consider to be the safest behavior - create a copy of the data (in the store) - modify the copy + the original.

What I consider the most correct behavior would be ```2.``` when we return the same pointer and there is only one instance of data in store, which would also be mutated -- I consider that is the responsibility of the user to be dealing with the pointers. We basically do the inplace operation and return the same object (in our case is the pointer on which we apply the inplace operator). If the user does a ```get``` on one of the pointers then they should know that the other pointer is invalidated.

**Comment by madhavajay** [comment]
@gmuraru Are we confident its a copy? After all the python code should only be returning a pointer to the inplace operator which in this case might just be a view. Perhaps PyTorch is simply not GCing the underlying data until both views of the data are freed.

Perhaps we can try this with another inplace operator that is destructive like sub_, add_ etc?
