### ISSUE TITLE
How can we start training from workers?

### ISSUE THREAD

**Issue by Nazila-H** [OpenMined/PySyft#4780]
## Question
How can we start training from workers?

## Further Information
Hi everyone,

For Horizontal Federated Learning we have a class called TrainConfig which seems that sends a model with network parameters to the workers. In the workers the training will happen then the results will be transferred to the server. In the whole process it seems that all the forward/backward propagation will be handled by the TrainConfig class. Do we have another similar class that build the model in the worker and start forward/backward propagation from/to server?

Thanks in advance
## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
