### ISSUE TITLE
TenSEAL framework missing for CKKS encryption

### ISSUE THREAD

**Issue by mgale694** [OpenMined/PySyft#4784]
## Description
Trying to run the homomorphic encryption via CKKS in the OpenMined tutorial. The syft.frameworks.tenseal is missing.

## How to Reproduce
1. Go to https://blog.openmined.org/what-is-homomorphic-encryption/
2. Run the CKKS tutorial

## Expected Behavior
Tutorial should run

## Screenshots
![Screenshot 2020-11-05 at 14 11 20](https://user-images.githubusercontent.com/51291404/98251580-c8c3b780-1f70-11eb-8b65-52c8858f9de7.png)

## System Information
 - OS: macOS Catalina
 - OS Version: 10.15.5
 - Language Version: Python 3.7
 - Package Manager Version: Venv

**Comment by boris-vasilev** [comment]
Looking at https://github.com/OpenMined/TenSEAL/issues/19 it seems like if you want to use syft.frameworks.tenseal you have to use the [tenseal/ckksvector](https://github.com/OpenMined/PySyft/tree/tenseal/ckksvector) branch. But it seems like adding CKKSTensor won't be merged into master anytime soon due to the technical challenges faced.

I also tried running the tutorial but after using [tenseal/ckksvector](https://github.com/OpenMined/PySyft/tree/tenseal/ckksvector)  I got the following error even though the import succeeded:

![image](https://user-images.githubusercontent.com/12242041/98362780-ba83a300-2025-11eb-8635-1c515eb774a8.png)

**Comment by youben11** [comment]
As @boris-vasilev explained, the use of ckks isn't yet fully supported in PySyft. We are working hard on TenSEAL to make the integration as soon as possible.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.

**Comment by macknight** [comment]
has this been resolved?

BR

**Comment by noamsuissa** [comment]
update on this?
