### ISSUE TITLE
comparison between FPT and AST is broken for SNN protocol

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/PySyft#4786]
## Description
Comparison operations mainly <, >, ==, <=, >= are broken for SNN protocol when we use it for FPT and AST.

## How to Reproduce
![Screenshot 2020-11-06 at 1 01 54 PM](https://user-images.githubusercontent.com/28955148/98338478-41d61400-2030-11eb-81be-6cac8899dfb7.png)

## Expected Behavior
it should be working as same as its working for FSS protocol
![Screenshot 2020-11-06 at 1 02 59 PM](https://user-images.githubusercontent.com/28955148/98338590-68944a80-2030-11eb-9615-7533da639108.png)

**Comment by ayush12gupta** [comment]
I am new to this project and wish to contribute to it I have gone through all the tutorials. Can give a try to this issue

**Comment by aanurraj** [comment]
Yes @ayush12gupta go ahead!

**Comment by aanurraj** [comment]
@ayush12gupta updates?

**Comment by ayush12gupta** [comment]
I read the about the implementation of snn through its paper and not trying to understand the code structure

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
