### ISSUE TITLE
Which function is used for serializing the tensor and deserializing the string to tensor?

### ISSUE THREAD

**Issue by Nazila-H** [OpenMined/PySyft#4788]
## Question
Which function is used for serializing the tensor and deserializing the string to tensor?

## Further Information
Hi everyone,

I want to serialize the tensor and send it from the worker side to the server side and deserialize, which function can I use for this purpose?

Thank you in advance.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
