### ISSUE TITLE
Implement memory-time trade-off for FSS-protocol

### ISSUE THREAD

**Issue by NiWaRe** [OpenMined/PySyft#4790]
## Description
The comparison between two SMPC-encrypted variables using the FSS-protocol works well as longs as the size of the tensors to compare is small- to medium-sized. 
E.g.: Computing `.argmax()` (to get predictions from the softmax output in a classification setting for instance) for a classifier with only 10 classes (e.g. a Classifier for Cifar10) works fairly quickly. 

However, if we compare a thousand class-scores to each other e.g. (as is the case for a classifier working on ImageNet) the FSS protocol leads to a memory-overload because of all the crypto-primitives necessary for this comparison. 

It would be nice to have sort of a dynamic mechanism that adds rounds to the protocol to reduce the needed crypto-primitives and hence the necessary memory, this way we make sure the host machines don't suddenly break down if one compares too many class-scores for example. 

## Are you interested in working on this improvement yourself?
- Possibly in the next weeks. If somebody wants to take this, however, feel free to do so. 

## Additional Context
As discussed with @LaRiffle

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
