### ISSUE TITLE
Add Super Resolution Example Duet Notebooks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4796]
## Description
Add two notebook's which reflect the Super Resolution example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/blob/master/super_resolution/

## Definition of Done
The partially runnable Super Resolution example notebooks should be in the examples/duet/super_resolution folder and a README.md should be added in the parent examples/duet directory with a link to the original example and our notebook.

**Comment by Koukyosyumei** [comment]
@madhavajay 
Hi, I am working on this issue, and I have almost done it. But, I already have a PR (#5071 ) to fix #4798. So, should I wait for #5071 to be finished, or may I create another PR for this issue?  Also, one possible plan is committing the notebooks for this issue within #5071 which I made for the DCGAN issue. I would like to hear your opinion because I'm not familiar with contriution to open source project. Thank you in advance.
