### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by gauravkumar411** [OpenMined/PySyft#4802]
## Description
The WebsocketClientWorker refuses to connect to the mentioned port.

## How to Reproduce
1. Convert both the notebooks WebsocketServerWorker.ipynb and WebsocketClientWorker.ipynb as python files
1. Run file WebsocketServerWorker.py
2. Run file WebsocketClientWorker.py
4. See error: [WinError 10061] No connection could be made because the target machine actively refused it

## Expected Behavior
A successful connection of client to the server and exchange of data

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.7
 - Package Manager Version: pip 20.2.4

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
