### ISSUE TITLE
Add model location to printout

### ISSUE THREAD

**Issue by NiWaRe** [OpenMined/PySyft#4803]
## Description
When printing out the model a description of the architecture is always outputed no matter if the model is stored locally or remotely on a worker. 
This is convenient, but it would be useful to also include the location (local or remote) of the model into the printout, to be able to quickly check where a model is currently stored. 

## Are you interested in working on this improvement yourself?
- Potentially doing it if nobody is interested in the next week. 

## Additional Context
As discussed with @gmuraru and @LaRiffle

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
