### ISSUE TITLE
Print warning if calling fix_precision() on a CUDA-tensor

### ISSUE THREAD

**Issue by NiWaRe** [OpenMined/PySyft#4804]
## Description
Currently when calling fix_precision() on a CUDA tensor will automatically first shift that tensor to the CPU to then call fix_precision() on it. It would be useful to issue a warning whenever this happens to warn the user that he might have intended to let the tensor be implicitly shifted to the CPU. 

## Are you interested in working on this improvement yourself?
If nobody is interested in the next week I could do it. 

## Additional Context
As discussed with @gmuraru and @LaRiffle

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.

**Comment by NiWaRe** [comment]
Closed through #4859
