### ISSUE TITLE
DataCentricFLClient. serve_model does not have correct path for PyGrid

### ISSUE THREAD

**Issue by jackhart** [OpenMined/PySyft#4809]
## Description
[The path set in DataCentricFLClient.serve_model](https://github.com/OpenMined/PySyft/blob/e1933a4a3c439964b8a92a158f6777819a1fcc34/syft/grid/clients/data_centric_fl_client.py#L230) is `/data_centric/serve-model/`, but the actual path is `/data-centric/serve-model/`.

## How to Reproduce

```
hook = sy.TorchHook(torch)
model_reg = DataCentricFLClient(hook, "http://modelregistry:5005") 

# code for building your model Plan
....

success = model_reg.serve_model(model, model_id = "test")
```

## Expected Behavior
Return a bool indicating of post was a success.

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
