### ISSUE TITLE
syft.workers.node_client module

### ISSUE THREAD

**Issue by khadija564** [OpenMined/PySyft#4818]
## Question

Does Syft.workers.node_client already a module in syft or we have to define it separately since when i tried running it, error popped up
## Further Information
![image](https://user-images.githubusercontent.com/26617882/99209984-aa837480-2818-11eb-9a70-ba7864216856.png)

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

## Additional Context
![image](https://user-images.githubusercontent.com/26617882/99209901-6ee8aa80-2818-11eb-962f-b6a8744f01f1.png)

**Comment by madhavajay** [comment]
Hi @khadija564 what was the error which popped up?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
