### ISSUE TITLE
Duet: sending an object twice with the same tag results in duplicate objects

### ISSUE THREAD

**Issue by bcebere** [OpenMined/PySyft#5043]
## Description
Duet: sending an object twice with the same tag results in duplicate objects, and the DS cannot retrieve it anymore.

Reproduced with the TenSEAL  notebook.

Sending the context once is fine and the DS can retrieve it
```
ctx_ptr = context.send(duet, searchable=True, tags=["context"])
duet.store.pandas

	ID	Tags	Description
0	<UID: 5061f0db8a824e4f90c8295cc745cd0d>	[context]	
```

Running the cell again and sending the context results in a duplicate tag in the store
```
ctx_ptr = context.send(duet, searchable=True, tags=["context"])
duet.store.pandas

	ID	Tags	Description
0	<UID: 5061f0db8a824e4f90c8295cc745cd0d>	[context]	
1	<UID: 16557f39c8cc413aacd640d50e5995af>	[context]	
```
Now the DS instance fails to get the context with
```
[2021-01-20T18:32:20.696733+0200][CRITICAL][logger] 'More than one item with tag:context'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-cad91c8e2dae> in <module>
      1 # STEP 1 Get pointers to the two encrypted vectors
----> 2 ctx_ptr = duet.store["context"]
      3 enc_v1_ptr = duet.store["enc_v1"]
      4 enc_v2_ptr = duet.store["enc_v2"]

~/anaconda3/envs/pysyft/lib/python3.8/site-packages/syft/core/node/common/client.py in __getitem__(self, key)
    430                 return match_obj
    431             elif matches > 1:
--> 432                 traceback_and_raise(KeyError("More than one item with tag:" + str(key)))
    433 
    434             traceback_and_raise(KeyError("No such request found for id:" + str(key)))

~/anaconda3/envs/pysyft/lib/python3.8/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
     57     except BaseException as ex:
     58         logger.debug("failed to print exception", ex)
---> 59     raise e
     60 
     61 

KeyError: 'More than one item with tag:context'
```

## System Information
 - OS: Ubuntu 20.04
 -  Python 3.8.5

**Comment by xutongye** [comment]
I have some thoughts about this issue.
1. The problem is not that "duet.store has multiple elements with same tags". I think it's okay and reasonable.
2. And "we can't call `duet.store['context']` when there are multiple elements with tags=['context']" is also not the real problem. Because it's natural that syft can't figure out  which one to return when there are mutiple ones match. The right way in this case is to use `duet.store["5061f0db8a824e4f90c8295cc745cd0d"]# use id` or `duet.store[0] # use index`.
3. But it is truly a problem that "multiple ptrs in duet.store pointing to the same object, if we send a same object multiple times." This is a bug we want to fix. And I have one optional solution in mind:
    1. The method `SaveObjectAction.execute_action` is where we put an object into `node.store`.
    2. In this method, before we do anything, we should first check if there already exists an object with the same id.
    3. If so, we just do nothing. Becuase the object we want to put into store is already there.
    4. Else, we do what should be done normally.

**Comment by madhavajay** [comment]
@xutongye also perhaps rather than rely on ID we could look at a hash since we use that already for signing.

**Comment by madhavajay** [comment]
I think we should be able to fix this with a client side registry which tracks duplicates and introduce the unique shared network `var_name`.
