### ISSUE TITLE
Running MNIST Notebook files as Python Scripts

### ISSUE THREAD

**Issue by sek22** [OpenMined/PySyft#5068]
## Question
**Can the MNIST files be run as standalone python scripts?**

## Further Information
I have downloaded the ipynb files to py files and want to run it locally. I have no qualms with copy and pasting the big hashes from the data owner to the data scientist script. I was wondering what is causing the setup to not work even though I have added some timeout to both scripts.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Windows 10
 - OS Version: 1909
 - Language Version: Python 3.8
 - Package Manager Version: Conda 4.9.2

## Additional Context

[python_files.zip](https://github.com/OpenMined/PySyft/files/5882839/python_files.zip)

**Comment by madhavajay** [comment]
The background asyncio tasks require a Thread to run in. In Jupyter this is provided, in the python interpreter in REPL mode we create one, but when running .py scripts we do not because we are looking for a solution that will allow us to not use the thread for certain implementations of Python which have threads disabled.

In the mean time you can just edit the `event_loop.py`:
```
# REPL requires us to create the Thread and Exit handler
# if not is_jupyter and is_interactive and SYFT_USE_EVENT_LOOP_THREAD:
if True:
    event_loop_thread = EventLoopThread(loop=loop)

    def exit_handler() -> None:
        info("Shutting Down Syft")
        if event_loop_thread is not None:
            event_loop_thread.shutdown()

    atexit.register(exit_handler)

__all__ = ["loop", "event_loop_thread"]
```

Once that is done then you can run two separate processes and they should work however there appears to be some multiprocessing issues so it depends on how you launch them.

We are working on some deeper integration tests which will iron this out soon.

**Comment by madhavajay** [comment]
@sek22 We now have CLI based Integration tests between Duet running as Python code, in this case actually converting a notebook to python code first but the result is the same:
https://github.com/OpenMined/PySyft/blob/c7018768e9a7d78da8c93cbf39d564713bca7968/.github/workflows/pr_tests.yml#L222
```
      - name: Run notebook Duet examples
```

Does that solve your issue?
