### ISSUE TITLE
Documentation Docstrings

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5109]
## Description
The team voted and agreed on Google Docstrings format.
Convert all docstrings to google format:
https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings

Find a plugin or lint checker which can check these for us.

## Definition of Done
We have a checker to find all the docstrings that are wrong and can fix them.

**Comment by J0** [comment]
@madhavajay can I work on this?

**Implementation Plan**
1.  Install  docstring linter like [darglint](https://github.com/terrencepreilly/darglint)
2.  Progressively correct all docstrings

Not sure if there's more to it

**Comment by madhavajay** [comment]
@J0 Spot on! If you can open a PR with darglint added to the `pr_tests.yml` in the `python-linting` step that would be awesome. We should make it not fail for now but progressively make it harder so that we are forced to refactor these docs.

**Comment by madhavajay** [comment]
@J0 it also looks like they support `pre-commit` so adding it to that makes sense since it gets run in the `pr_tests.yml` linting step above.
```
repos:
-   repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
    - id: darglint
```

**Comment by J0** [comment]
Cool, will file a PR shortly. Thanks!

**Comment by J0** [comment]
Hey,

Reposting from Slack so we can attempt to get more views. 

I'm currently working on introducing a doc linter to `PySyft` so that we conform to the Google docstring format. I was just looking through the codebase and I realized that the existing docstrings are formatted according to Sphinx Style so that PySyft can generate docs. This would mean that I can't remove the Sphinx Style comments at they would affect doc generation.

I was thinking of introducing a Sphinx extension like [Napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) and subsequently replacing the Sphinx docstrings with Google Style docstrings. Just wanted to get your thoughts on this and check if there are alternative workarounds and if you forsee any potential portions of the docs breaking because of the introduction of this new extension.
