### ISSUE TITLE
Refactor out test data from torchvision allowlist

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5325]
## Description
Refactor out all the test data in the `torchvision/allowlist.py` into another file, either in the tests or `.json`.

## Definition of Done
Remove: `"test_parameters": "(tens, angle = 10)",` from `torchvision/allowlist.py`.
Double check min_version requirements, since PIL inputs are not prohibitive in binding to the AST.

**Comment by vsquareg** [comment]
Created a PR #5383

Re-factored out all `test_parameters` to `allowlist_test_params.json`.

Updated relevant min_version requirements for PIL inputs.

**Comment by vsquareg** [comment]
To support older versions of torchvision (methods with only `PIL.Image.Image` as argument type), I believe we need to load the PIL library by default. This is required for both, to modify the tests to pass and during runtime (since `PIL.Image.Image` would have to be used anyway). 

Or are there any other workarounds I could look at?
