### ISSUE TITLE
Change Plans Placeholder Type API

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5358]
## Description
Change Plans to use a less confusing API for annotating the Placeholder Pointer types.

Currently this `inp` variable results in the type: `TensorPointer`.
But a real tensor of that shape is used during tracing.
```python
@make_plan
def add_plan(inp=th.zeros((3))) -> th.Tensor:  # type: ignore
    return inp + inp
```

However it looks confusing and could potentially be easy to make mistakes with.

So perhaps this could be written another way.

```python
@make_plan
def add_plan(inp=PlaceHolder[FloatTensorSized(3)]) -> th.Tensor:  # type: ignore
    return inp + inp
```
Potentially creating the required sized Tensor and sending it under the hood?

We could always fall back to the normal way as well for types where we dont have some kind of nice API.

This definitely needs some consideration.

## Definition of Done
The existing way to declare types and default values for tracing is made less confusing.

**Comment by koenvanderveen** [comment]
I agree that this API is currently not as intuitive as it could be. I wonder if introducing PlaceHolders would make it less confusing, because it is another abstraction to understand. What would be the use of that abstraction, because I believe that we are only using local objects and pointers to objects when creating plans. We could also make the sending part more explicit, but maybe with a shorter notation by overloading `@` to send?
```
@make_plan
def add_plan(inp=th.zeros(3)@plan_vm, inp2=th.zeros(5)@plan_vm -> th.Tensor:  # type: ignore
    return inp + inp
```

**Comment by madhavajay** [comment]
During discussion with @koenvanderveen we thought maybe an `Alias` type for all of the Torch Shaped types would be a good way to go.
