### ISSUE TITLE
Plan Source Code

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5359]
## Description
Add additional string representation of the code of traced plan function to be sent with plan for preview:

```python
@make_plan
def my_plan(data, arg2):
	y = data + data
	z = y * y + arg2

    output = {}
    output['z'] = z
    output['y'] = y
	return output

print(my_plan.code):
"""
@make_plan
def my_plan(data, arg2):
	y = data + data
	z = y * y + arg2

    output = {}
    output['z'] = z
    output['y'] = y
	return output
"""
```

This will allow the DO to look at the code which was used to generate the plan and eye ball what its doing.
Later we will make this more secure by compiling on the DO side.

**Comment by koenvanderveen** [comment]
When we do:
`y = data+data`
Do we store the name "y" in the `StoreObjectAction`? Probably not right? Do we want (and is it feasible) to do this? Otherwise we would get something like:
```
var1 = data+data
var2 = var1*var1 + arg2
```

Also, I dont think we can infer whether multiple operations were chained on one line, so I think we cannot infer whether it was

`z = y * y + arg2`

or

```
z1 = y * y
z = z1 + arg2
```

it would make a bit of difference though, because if we don't have these things we might choose to improve the representation for individual actions, and just make the plan add some boilerplate (@makeplan def ...), and replace e.g. "UID123" -> "var1"

**Comment by koenvanderveen** [comment]
or do we just use something like `inspect.getsource(func)`, that would be pretty easy, but not very secure if we rely on this representation for approving execution

**Comment by madhavajay** [comment]
@koenvanderveen I personally was thinking it would be cool to re-construct the code from our actions and assign variables, and perhaps we might look at some kind of Plan decompilation step later but I think the goal right now is to do `inspect.getsource` so that its verbatim the same code you used to create it. If it worked on the DS side it should work on the DO side, so later we can optionally do the compilation on the DO side to provide some level of confidence in the Plan being untampered.
