### ISSUE TITLE
Improving Dict Iterator creation

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5365]
## Description
Currently, if you trace it, we are making 4 remote `__len__` requests when creating a Dict/OrderedDict remote iterator. Ideally, we should stick to one. The same goes for any Iterator that is being created from Dict (`.values()`, `.items()`, etc).

Snippet to reproduce:
```
import syft as sy
client = sy.VirtualMachine().get_root_client()
iter(client.syft.lib.python.collections.OrderedDict({1: 1, 2: 2}))
```

with a `print(attr_path_and_name)` in `syft/ast/klass.py` at the top of the function `run_class_method`.

**Comment by vsquareg** [comment]
This is caused due to the `__iter__` being wrapped multiple times by:

https://github.com/OpenMined/PySyft/blob/261869e50852a24b2d76f3b44a5819050acd9eb8/src/syft/ast/klass.py#L338-L342

For `OrderedDict`: (`items`, `values`, `keys`) return an `Iterator`, hence the  `__iter__` gets wrapped thrice.

I believe the wrapping was done in this manner to account for types that can't be iterated directly (no `__iter__`) but have inbuilt functions that can return an `Iterator`.

To avoid the wrapping multiple times, either a flag can be added within this `for` loop (seems better to me).
Or`wrap_iterator` function can check if `__iter__` has already been wrapped, and skip re-wrapping it.

@tudorcebere if this seems fine, I'll create a PR.
