### ISSUE TITLE
Audit pygrid tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5434]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by marcalph** [comment]
I'd like to work on this! I'll open a PR today

**Comment by TimVanMourik** [comment]
Hey Team, I recently found PySyft/PyGrid and (upon request) wanted to share some of my feelings and findings and the things I came across. This is mostly a log of my steps, so see it as a first-time-user-report. I'm a user that is skilled in full stack and data science and conceptual (not hands-on) federated learning.

### Progress log
* In order of appearance, it looks like the latest PySyft install is broken. I'm assuming this is known, but as a newbie it set me back a bit.
* I loved the titles of the course sessions (courses.openmined.org) and wanted to check some of them out. I was disappointed to see that you can follow the course linearly only (at least I didn't manage to skip anything), because I'm familiar with the basics already. It was a lot of clicking and waiting to get to the good part. IMO, the courses are weak as courses, but _incredible_ as the backbone of documentation.
* Then: which tutorial to start with? PySyft tutorials seemed like the best option. 
  * Starting with: `examples/api/start.ipynb`. It's alphabetically the first with `api` and his has `start` in there, so maybe it's number one? It worked out of the box so that was very nice. It was also a bit complicated and dry and after running it's only a couple of days later that I understand what happened :) It would be really cool if the flow of this notebook is documented in a diagram!
  * Next, I found the `private-ai-series/duet_basics` Owner-Scientist dual example. This one is *AMAZING*. I loved how it worked out of the box and solves the problem why I landed with PySyft in the first place. This is my personal interest, so this should have been my first tutorials, but maybe others feel differently. 
    * Minor details on the tutorial: The very first commands `duet = sy.launch_duet(loopback=True)` would be improved with a comment on how to change it for a collaborative duet. I believe something like `duet = sy.launch_duet("SOME_SECRET", loopback=True)` would do the trick
  * For my use case, I'm really interested in a use case beyond peer-to-peer and for multiple clients in the network. I realised that's what PyGrid is for. So I went to check out the `examples/pygrid` tutorials.
    * This is where things got hairy. I first went to the `PyGrid` repository, but those examples were out of date and rather minimal. 
      * The imports were specific for `syft==0.3.0` and I had to update them by looking through the code (see Slack). 
      * The tutorial starts with authentication, but there's no documentation on how to create that first user. I used a manual curl request and to my surprise it worked `curl --request POST http://localhost:7000/users --header 'Content-Type: application/json' --data-raw '{"email": "admin@email.com", "password": "pwd123”}’`.
      * There are 3 different ports used (5000, 5001, 7000) in the scientist/owner notebook. I can see how different users might be on different ports, but explanation would be nice :)
      * The `Create a new users` block failed. My hunch was that the permissions to create users with certain roles are updated because the first user is created but not the second. I stopped here, because I didn't feel like going more into the depths of the code. 
    * I moved to PySyft tutorials in the PyGrid folder. I wanted to start with the basics. 
      * I started with the `user` folder, but I got the same problem as above, so quit this pretty quickly. And my Hackathon was over.
  * In the Duet basic example I quickly replaced the sample age data for fake patient data that is produced by our internal application. I showed the example to others and people were very enthusiastic. So I definitely got a go signal to continue exploring if we can use PySyft and collaborate. Will keep you posted :) 

### General thoughts about dependencies
I am in general a little confused about the relationship between PyGrid and PySyft. PyGrid seems to be a server that handles PySyft requests, full fledged with user and permission management. It has a dependency on PySyft but I'm not sure if that's necessary, i.e. if it's doing syfty things, or if it's just delegating generic peer-to-peer connections. Conversely, I'm not quite sure to what extend PySyft is modelled towards PyGrid or if PyGrid could easily be exchanged for 'some other access management tool'. 


### Concluding remarks
So, these are my thoughts. Please feel free to move this report elsewhere, because it might be cluttering the ticket. Don't feel obliged to answer the questions I have here, I'm just pointing out that these are the questions a first time user might have. Thanks for your work on this, I'm going to continue diving into the OpenMined libraries :)

**Comment by jmaunon** [comment]
Thanks a lot!
Your feedback is very very useful. I share your opinion and this is part of the work that must be done!

I close this issue because this was the goal
