### ISSUE TITLE
Error returns 200 code

### ISSUE THREAD

**Issue by gkaissis** [OpenMined/PySyft#5752]
## Description
[This line ](https://github.com/OpenMined/PySyft/blob/4f276a97fef6b779822437fa7d54e21ff4d8dd1a/packages/grid/apps/worker/src/main/core/services/tensor_service.py#L156) describes an error response, which gives a 200 HTTP code. Should this be `success=False`?.

**Comment by tudorcebere** [comment]
@IonesioJunior can you help?

**Comment by tcp** [comment]
The same behavior happens for `create` and `update` routes.

I can have a go.

@IonesioJunior

**Comment by IonesioJunior** [comment]
Hello @gkaissis, glad to see you! :smiley: 

Initially, the idea of ​​returning rest codes in PyGrid messages was something in our development plan. Over time, due to planning changes and the possibility of the Syft library working with different protocols, this lost some of its semantic meaning. Currently, `status_code=200` is returned by default on all messages (unless an internal error has occurred) just to not break things.

We intend to remove this field in the next versions in order to delegate the responsibility to the frameworks of an external layer (without creating a dependency between the Syft library and the communication protocol used).

In the future, services will be developed following [this pattern](https://github.com/OpenMined/PySyft/blob/785fd8a29e6f8db20ac7b3b159b5842b4c1a8509/packages/syft/src/syft/core/node/common/node_service/service_dataset_manager)

In case of an HTTP request, the code returned will be managed by an external layer, responsible exclusively for handling messages using this protocol.

My apologies for the mistake created.

**Comment by tcp** [comment]
@IonesioJunior quick question: what apps are dependent on the grid api error messages?
