### ISSUE TITLE
Can we have an updated documentation of the latest version of pysysft ???

### ISSUE THREAD

**Issue by Chris-george-anil** [OpenMined/PySyft#6042]
It would make it really easy to use this Framework, and use it to its full potential

**Comment by RoyRin** [comment]
Yes, seconded!

I've even tried generating the docs using Sphinx, and I only found documentation on Hagrid - since most of the tutorials are pre 0.3.0 (https://blog.openmined.org/federated-learning-additive-secret-sharing-pysyft/) it's unclear what the expected flow is.

Documentation can be a lot and can slow down development speed, but even just some updated tutorials would be really helpful!

**Comment by IrinaMBejan** [comment]
Hey @RoyRin and @Chris-george-anil, thanks for adding this issue - we are working on better docs for PySyft.

You can find here a few tutorials on using and deploying PySyft + PyGrid and the API documentation. It's still work in progress, but happy to hear your feedback: https://openmined.github.io/PySyft/index.html#

We will work on adding more tutorials similar to the outdated ones and I'll try to add updates on this current thread. If you want to contribute, let me know!
