### ISSUE TITLE
Example Links for using PySyft.

### ISSUE THREAD

**Issue by meetgandhi123** [OpenMined/PySyft#6411]
## Description
I am a student and want to use PySyft for a federated learning-related project but all the blogs and even the official links I open have the code for older versions of PySyft and understanding where to get started is really difficult for me. Can you please provide some links for basic examples like doing image classification using PySyft? 

## Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by lidh15** [comment]
Man, when I clicked this issue I was expecting to see the maintainer's replies on example links (there were some examples in 0.3.0 but removed in the latest, wtf!), but no replies are seen after four weeks. 
I have to say pysyft is one of the most ridiculous python libraries that every api is f**king no longer supported in the next minor version and the demos and docs are as perfunctory as an 8-star high school homework repo rather than 8k-star it has. lol

**Comment by meetgandhi123** [comment]
Hey, you can use Tensor flow Federated. It's very well documented !!! I ended up using that..

**Comment by madhavajay** [comment]
We understand peoples frustration but the changes between versions have been necessary and based on discoveries we have made over the iterations while implementing the latest research. We were unable to triage all of the github issues while working to deliver the latest version for the community. That time is very close and `dev` which will soon be `0.7.0` is about to be released. We already have stable beta releases weekly on PyPI and dockerhub all of which are tested against our integration test suite.

Recently we were accepted to GSOD so we have two great docs team members who will be working with us to update all the documentation to our biggest release.

Thank you for your patience. You will see in the commit logs we have been working constantly since the last release to completely overhaul the tech stack to support our user friendly Automatic Differential Privacy and Secure Multi-Party Compute solution which can be deployed to a variety of platforms using our cli tool hagrid.

We are looking forwards to sharing the 0.7.0 release with everyone shortly.
