### ISSUE TITLE
Tutorials & Examples 

### ISSUE THREAD

**Issue by rish2410** [OpenMined/PySyft#6529]
Hello Team

I was watching Andrew Trask video on YouTube and saw that he was explaining Homomorphic Encryption via **tutorials and examples** from Openminded/PySyft github . Also I saw some blogs with link regarding tutorials but that page doesn't exists .

Could you please make it available as I am new to this topic of Homomorphic Encryption for Machine learning models .
And I am trying to build on POC with simple example of Linear or Logistic regression .

It will be helpful if I get some notebooks and documentation of this library for Homomorphic Encryption of ML models.

Thanks and Regards,
Rishabh

**Comment by madhavajay** [comment]
Hi @rish2410 there is a lot of HE content in our older branch here:
https://github.com/OpenMined/pysyft/tree/syft_0.5.0
https://github.com/OpenMined/PySyft/tree/syft_0.5.0/packages/syft/examples/homomorphic-encryption

I can highly recommend you checkout the Course 2 content:
https://courses.openmined.org/

For our latest version `dev` (0.7.0 release coming soon), we have gone for `SMPC` instead of `HE` because it executes faster.
