### ISSUE TITLE
Running Syft and Hagrid on Google Colab

### ISSUE THREAD

**Issue by factdroid** [OpenMined/PySyft#6713]
## Question
**Describe your question in ONE SENTENCE.**
- Can one run syft and hagrid on Google Colab? 

## Additional Context
- Which versions can be run on Google Colab if any?

**Comment by madhavajay** [comment]
![image](https://user-images.githubusercontent.com/2882739/190067745-1319b7f9-7dbc-45bf-b866-8699455bb84f.png)

I just tested it and it seems to work fine. We do intentionally test Python 3.7 in CI because Google Colab refuses to get with the modern Python times.

<img width="293" alt="Screen Shot 2022-09-14 at 3 35 07 pm" src="https://user-images.githubusercontent.com/2882739/190068046-d0737826-1fa7-461d-9004-25593f2708c8.png">
