### ISSUE TITLE
Unable to get object

### ISSUE THREAD

**Issue by ktobah** [OpenMined/PySyft#6781]
## Description
Following your guidelines, I installed the latest pre-build of syft and started hagrid successfully. I, then, started following your notebook examples, so I created a domain, prepared, and uploaded a dataset example.

When I reach the step of accessing the tensor with get() in this [notebook](https://github.com/OpenMined/PySyft/blob/dev/notebooks/course3/L5_Data_Scientist.ipynb) , I get an exception (see screenshot below). Any help, please?

I would also like to mention, that most of your notebooks seem outdated and don't work with the latest build 0.7.0.

## How to Reproduce
1. Open the notebook in the link, and follow along.

## Expected Behavior
You should get the results as in the notebook.

## Screenshots
![image](https://user-images.githubusercontent.com/3786785/192176339-67ca223d-0169-4ef9-9755-1146247bf389.png)

## System Information
 - OS: [Ubuntu]
 - Language Version: [Python 3.9]
 - Package Manager Version: [Conda]
 - Browser (if applicable): [Google Chrome]

**Comment by ktobah** [comment]
I changed the dataset selected, and somehow it worked now. So, if you think this has to do with the dataset uploaded having an issue, please close the issue.

**Comment by madhavajay** [comment]
@ktobah these are the course notebooks which we test in CI on every PR:
https://github.com/OpenMined/courses/tree/introduction-to-remote-data-science-dev

We will be adding some better tooling to help trace issues when they occur but unfortunately we can't just send back a normal exception to the client user because that would allow them to figure out why their query failed and learn information about the dataset.

There are some stability changes happening as we speak in the `dev` branch which should make the usage of AutoDP more robust, once we release 0.7 officially the example notebooks with some presupplied datasets we are building should work.

I can highly recommend you tail the logs of your `celeryworker` container when you publish. If there is an error it will appear there.

**Comment by ktobah** [comment]
Thank you for the hints. I will check that.

**Comment by madhavajay** [comment]
@ktobah I assume this is resolved so will close this for now.
