### ISSUE TITLE
GSoD: Quickstart notebooks for data scientists

### ISSUE THREAD

**Issue by ShubhamPalriwala** [OpenMined/PySyft#6856]
## Where?
We would like to extend the quickstart section of the documentation with the following tutorials for the data scientists:

- [ ] Connect to a Domain @abhiwalia15 
Learning objective: How one can connect to a domain with a data scientist

- [ ] Searching for Datasets on the Domain @ShubhamPalriwala https://github.com/OpenMined/PySyft/pull/6871
Learning objective: How one can look for datasets after connecting to a domain and select one getting its information

- [ ] Exploring a Dataset on the Domain @ShubhamPalriwala https://github.com/OpenMined/PySyft/pull/7045
Learning objective: How one can select a dataset and view its description and try out a couple of tensors on the dataset

- [ ] Performing Data Science
Learning objective: Fun tutorials of remote data science something like the ones suggested by Ishan and Shubham

- [ ] Retrieving Secure Results
Learning objective: How one can securely fetch results from the model remotely

## Who?
New users to OpenMined looking to learn how to use PySyft as a data scientist.

**Comment by IrinaMBejan** [comment]
Hey @abhiwalia15, assigning you on the task as well together with @ShubhamPalriwala :) Thank you both for the contributions!

**Comment by abhiwalia15** [comment]
@shubham3121 please assign this task to me. Thanks 😊

**Comment by Kiaka007** [comment]
# Feedback on quickstart docs

## Data Scientist  Connect to Domain tutorial:
* Data Scientists are end users who want to perform computations or answer specific questions using the dataset(s) of one or more data owners. The very first thing Data Scientists have to do in order to submit their requests is login and connect to the Domain Server that hosts the data they would like to make requests off of or to connect to a network by which they can search for different datasets. Today's tutorial will show you how you as a Data Scientist can connect to an organization's domain server using PySyft.
* For connecting to a Domain Server, we will use the login credentials assigned to us by the Domain Owner. By default, we as Data Scientists have the lowest level of permission to access the data (which means data is highly private) and will be assigned a Privacy Budget of 0.
* Overview of this tutorial:

- Obtain the Login Credentials
- Login to your Server
- Explore some useful starting commands (we could show how some useful starting commands work like listing datasets on the domain etc.)

**Note:
PyGrid Admin (the UI) is only meant to be used by domain or data owners so a data scientist would never login to the domain node via the UI.**


### Step 1 Obtain Login Credentials
* To utilize the privacy-enhancing features and play around with your privacy budget, as a Data Scientist you must first get your login credentials from the domain owner. What you will need to login to the domain server is the following information:
* **email**
* **password**
* **URL of the domain**
* **port of the domain**

**Note:
I am not sure if the commands in the cell of the current notebook are possible for a data scientist to use in syft. I need input from @shubham3121  As far as I know Data Scientists cannot just auto register themselves to a domain node.**

### Step 2 Login to the Domain as a Data Scientist
* Once you have the above information you can open a Jupyter Notebook and begin logging into the domain server.
* To start you will need to install syft 
* ``` import syft as sy ```
* Then you can provide your login credentials by typing:
* ``` domain = sy.login(email="____", password="____", url="____",port=8081) ```

### Step 3 Exploring a Domain Server
**Note:
It would be a good opportunity here to show some useful beginning commands for a data scientist like listing the datasets on this domain. @shubham3121 will have good ideas on what some starter ones could be.**

**Note:
Adjusting permissions and setting roles is not something a data scientist user does. It is something a domain owner does to create and manage users of the domain. So we should delete any steps here that point to the UI and that point to adjusting permissions.**

**Comment by Kiaka007** [comment]
# Feedback on quickstart docs

## Data Scientist Search for Datasets tutorial:
In the last tutorial, you learned as a Data Scientist [:doc:`How to Connect to a Domain Server <00-deploy-domain>`](https://github.com/OpenMined/PySyft/blob/8b049a5ed891f77016b1cac669a9f5be84175ee5/docs/source/guides/data-scientist/01-search-for-datasets.rst#id1) which allowed us to connect to our organization’s domain server.

Once connected to the domain, the first thing that we would want to do as a data scientist, is look for available datasets listed on the domain. Today's tutorial will be going over how we go about doing that.

### Step 2 Login to the Domain
* Let's login to our Domain with the credentials provided to us by the domain owner. If there is no domain or specific domain owner for you to try these steps out on then, you can create a domain node locally for yourself and act as a domain owner by following the tutorials starting here: [data-owner/00-deploy-domain](https://github.com/OpenMined/PySyft/blob/8b049a5ed891f77016b1cac669a9f5be84175ee5/docs/source/guides/data-owner/00-deploy-domain.html).

### Step 3 Search for datasets on the domain
**Note:**
Might want to add some descriptions as to what the different columns in the dataset list table mean. Like shape and assets etc.

**Comment by Kiaka007** [comment]
# Feedback on quickstart docs

## Data Scientist Explore a dataset tutorial:
**Image**
You can use: https://github.com/OpenMined/design/blob/assets/diagrams/exploring%20a%20dataset.png

## Step 8 Actually querying data
If you actually want to query data, you could do it by spending some of your privacy budget. This happens with the following 2 commands:

* .publish() uses your privacy budget limit approved by the data owner to query the actual data and produce a noised result that does not compromise the original dataset. The amount of accuracy and therefore the amount of privacy budget you spend here is determined by the sigma you define. Sigma in this case indicates the level of noise added to the final result; whether you want the range of your answer to be within an X estimated sigma of the true answer.
* get() to access the contents of the published_result pointer created above.
* **It is important to note that if you do not have enough privacy budget to receive a result with the specified sigma then you will instead receive a very noisy result. This is an indication that you need to request more privacy budget from the domain owner.**

## Step 10 View our final privacy budget
As you can see, your privacy budget got reduced. It is because we used the .publsh(sigma=x) and .get() methods to actually query the dataset. ~~Also, if you look deeply, your privacy budget used up is equal to the amount you used for the sigma!~~

**Note: I X'ed out the above because that statement is not true. The amount of sigma specified is not the same thing as the privacy budget used and in general the two values do not tend to equate to be the same value. Sigma is tied to the amount of noise added. I believe you can think of it in terms of standard statistics sigma as in sigma=1 indicates that I want my answer to be within 1 standard deviation of the true answer.

**Comment by shubham3121** [comment]
Data Scientist Connect to Domain tutorial:
Left comments in the PR:
https://github.com/OpenMined/PySyft/pull/7120#pullrequestreview-1220463155

@Kiaka007, yes it is currently possible to register to a domain if the user has the URL to the domain. Although, he will have a zero privacy budget allocated to him.

**Comment by shubham3121** [comment]
Data Scientist Explore a dataset tutorial:
Added comments here:
https://app.reviewnb.com/OpenMined/PySyft/pull/7045/

**Comment by abhiwalia15** [comment]
> # Feedback on quickstart docs
> ## Data Scientist Connect to Domain tutorial:
> * Data Scientists are end users who want to perform computations or answer specific questions using the dataset(s) of one or more data owners. The very first thing Data Scientists have to do in order to submit their requests is login and connect to the Domain Server that hosts the data they would like to make requests off of or to connect to a network by which they can search for different datasets. Today's tutorial will show you how you as a Data Scientist can connect to an organization's domain server using PySyft.
> * For connecting to a Domain Server, we will use the login credentials assigned to us by the Domain Owner. By default, we as Data Scientists have the lowest level of permission to access the data (which means data is highly private) and will be assigned a Privacy Budget of 0.
> * Overview of this tutorial:
> 
> * Obtain the Login Credentials
> * Login to your Server
> * Explore some useful starting commands (we could show how some useful starting commands work like listing datasets on the domain etc.)
> 
> **Note: PyGrid Admin (the UI) is only meant to be used by domain or data owners so a data scientist would never login to the domain node via the UI.**
> 
> ### Step 1 Obtain Login Credentials
> * To utilize the privacy-enhancing features and play around with your privacy budget, as a Data Scientist you must first get your login credentials from the domain owner. What you will need to login to the domain server is the following information:
> * **email**
> * **password**
> * **URL of the domain**
> * **port of the domain**
> 
> **Note: I am not sure if the commands in the cell of the current notebook are possible for a data scientist to use in syft. I need input from @shubham3121 As far as I know Data Scientists cannot just auto register themselves to a domain node.**
> 
> ### Step 2 Login to the Domain as a Data Scientist
> * Once you have the above information you can open a Jupyter Notebook and begin logging into the domain server.
> * To start you will need to install syft
> * `import syft as sy`
> * Then you can provide your login credentials by typing:
> * `domain = sy.login(email="____", password="____", url="____",port=8081)`
> 
> ### Step 3 Exploring a Domain Server
> **Note: It would be a good opportunity here to show some useful beginning commands for a data scientist like listing the datasets on this domain. @shubham3121 will have good ideas on what some starter ones could be.**
> 
> **Note: Adjusting permissions and setting roles is not something a data scientist user does. It is something a domain owner does to create and manage users of the domain. So we should delete any steps here that point to the UI and that point to adjusting permissions.**

https://github.com/OpenMined/PySyft/pull/7120/commits/92454540338268111fb317ebd9912bfbe437b976

**Comment by abhiwalia15** [comment]
https://github.com/OpenMined/PySyft/pull/7120/commits
