### ISSUE TITLE
UX Improvement: More hand-holding. When creating a Syft Tensor, tell DS they can annotate. After annotate, tell DS they can load_dataset

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6921]
It isn't obvious how a new PySyft user would know they had to call `.private` or `.annotate` on their Syft Tensor. Perhaps we could do some signposting and when a new Syft Tensor is created, we could print something like "Syft Tensor created! To activate Differential Privacy protection, please call `.annotate` and load into a domain node!"

**Comment by iamtrask** [comment]
I like this idea. I think this and other queries might be best turned on/off by a syft.helper=True flag (which could default to True)

**Comment by iamtrask** [comment]
This was actually opened by @IshanMi

**Comment by madhavajay** [comment]
We could also persist this `syft settings` to their `~` home directory the same way we do with `hagrid`.

**Comment by iamtrask** [comment]
> We could also persist this `syft settings` to their `~` home directory the same way we do with `hagrid`.

Stretch

**Comment by madhavajay** [comment]
I have had to disable this for now because every time a tensor gets created with internal code it prints. For SMPC this can result in hundreds of the same message getting printed.

https://github.com/OpenMined/PySyft/pull/7086

Let's create a new PR which enables this but does not trigger. Perhaps we could have a global timeout or something similar to prevent it from flooding prints?

**Comment by iamtrask** [comment]
Relying on a syft.helper = True flag seems like a reasonable middle ground. Default it to False and set it to True in all our tutorials.
