### ISSUE TITLE
TensorPointer docstring is not helpful when it comes to specifying which args and kwargs are supported

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6932]
numpy.copy has 1 arg/kwarg, numpy.ndarray.copy has 2 args/kwargs, it's not clear how many/which we support:

![Image](https://user-images.githubusercontent.com/32711264/199330803-c1bd2d07-be01-45ab-adda-580e9a4cb6e0.png)

**Comment by IshanMi** [comment]
Similar problems exist for other ops, such as concatenate:



![Image](https://user-images.githubusercontent.com/32711264/199331355-a6be2672-a150-44b9-80c3-0eb459c43c1c.png)

**Comment by madhavajay** [comment]
I guess the first one is just showing the default method signature as fallback. The question is can we annotate all these methods with the same strict method signatures as numpy. If so that would be great. If not, perhaps it needs to be added via the docstring, but unfortunately docstrings dont execute so they can quickly become invalid, so if we can change the actual signature first, I think that would be optimal.

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older versions of PySyft (<=0.7) and are not aligned in our current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
