### ISSUE TITLE
No way to easily check if a large DataSubjectArray is that of a GammaTensor or PhiTensor

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6934]
At the moment, we use checks like `assert len(self.data_subjects.sum()) > 1` to determine if a given data subject array belongs to a GammaTensor.

This is fine for small DSAs, such as in our unit tests- but when working on the Twitter notebook I noticed that this performance does not scale too well when calling `sum()` on a DSA with a large number of distinct Data Subjects.

It would be cool if there was a method like `DSA.is_gamma()` that would return True if even a single value in the DSA had >1 data subject in its set.
This is incontrast to sum, where you have to complete the entire summation operation even if you realized that summing the first two rows/elements itself tipped you off that it was a GammaTensor's DSA

**Comment by madhavajay** [comment]
Is this something which would act locally to just check the Pointer type?

Is this to allow a user to avoid running expensive operations on their Tensors if they are `gamma` because doing so causes its own issues of broken or slow / unresponsive Domain where you can't cancel actions in the queue? Or does it have another utility?

**Comment by madhavajay** [comment]
Ah I think I see now you're saying. I think that since we need to re-think the data structure for DSA so that it can handle dynamic updates we should add this to the requirements so what ever we build can identify if the tree of DSA data is `homogenous` or not. Although perhaps it's not needed at that stage. We could not convert `PhiTensor` to `GammaTensor` when its a root tensor and then it would be implied that its DSA would be singular, then allow composition from that point on.

https://github.com/OpenMined/PySyft/issues/7039

**Comment by iamtrask** [comment]
Flagging for 0.7 because other issues necessitate a refactor of DataSubjectArray and so we should take this issue into account during that process.

**Comment by kiendang** [comment]
@IshanMi this should be fixed by #7010 no?

**Comment by madhavajay** [comment]
@kiendang Great work, I think that is a big improvement over what we have now. Do you know what happens if DataSubjects get filtered in a root Tensor? I guess a Gamma can become a Phi technically? Not sure if that matters though.

**Comment by kiendang** [comment]
Hmm I haven't checked that. Also I think we could think about whether we should refactor this check out of `private` coz it might be useful elsewhere.

**Comment by IshanMi** [comment]
Closing- this was fixed by #7010
