### ISSUE TITLE
Pointer gets deleted if publish fails on the server side

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6938]
If during the `publish()` call, there's a server side error, the pointer to your result still gets exhausted/deleted.
It would be better experience if you still had the pointer, and could possibly still use it.

co-authored/found by @teo-milea

**Comment by madhavajay** [comment]
Is there a way to demonstrate / replicate this? From I see `ObjectDeleteMessage` only gets sent on `.get` so there should be no other way to delete stuff from the store. Perhaps the issue is just that the server side error is preventing future `publish` calls from working? Or the same one will result in the same error?

**Comment by teo-milea** [comment]
this might have happened before we caught #6953 so it could be solved by that
