### ISSUE TITLE
Order pysyft

### ISSUE THREAD

**Issue by Floev** [OpenMined/PySyft#695]
### User Story
pysyft.py is currently hard to navigate. We should order it!

### Discussion Points
Obvious route is alphabetic, ignoring __ and __i. 
Inline functions after returning functions and __ixxx__ after __xxx__

We could also put the __xxx__ ops first. And make another exception for __init__.

Thoughts?

**Comment by Floev** [comment]
Also, have we decided whether we want to expose the operators as functions as well?
E.g. def __add__ as well as def add

**Comment by diegoalejogm** [comment]
@Floev Good points!
Your navigation strategy sounds good to me. I'd categorize functions according to their job first (e.g. `no_params_func` is a different type of job than `_add_` or `_mul_`), and then reorganize lexicographically as you mention. What do you think?

Also, regarding the exposure of those methods, I think we should do it, so that we are still consistent with PyTorch:
<img width="393" alt="screen shot 2017-12-13 at 22 57 59" src="https://user-images.githubusercontent.com/4405152/33974964-8a20abea-e059-11e7-98de-44f30e048333.png">

**Comment by bosr** [comment]
@floev I'd like this too. In my PR https://github.com/OpenMined/PySyft/pull/701 (closed now), I ordered lexicographical inside semantic sections. Does this make sense?

**Comment by bosr** [comment]
I'm asking because as said in PR https://github.com/OpenMined/PySyft/pull/701 comments, I am about to re-submit it in 3 bits, the first bit being methods reorg. I'd like to know I'm on the right track / fits your goal too.

**Comment by iamtrask** [comment]
How do we feel about the current layout? The file was broken into pieces and seems certainly more organized before.
