### ISSUE TITLE
AttributeError: module 'syft' has no attribute 'join_duet'

### ISSUE THREAD

**Issue by FaisalAlshami** [OpenMined/PySyft#7624]
## Question

I got this error 
AttributeError: module 'syft' has no attribute 'join_duet'
when applying this code
duet1 = sy.join_duet("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
## Further Information
Describe your question in greater length here.

## Screenshots
![image](https://github.com/OpenMined/PySyft/assets/23058510/86ffda8e-aabc-4f69-ad9f-d36a38356025)

## System Information
 -  Torch 1.4.0
 - Torchvision 0.5.0
 - Syft 0.2.9

**Comment by iamtrask** [comment]
Duet did not exist in PySyft before 0.6. I recommend upgrading to PySyft 0.6 and trying again.

**Comment by Vicobarafor1** [comment]
Hello, I have been struggling to install pysyft on both my windows 10 and Mac OS Big Sur version 11.7.7 device since Thursday. I have followed different installation procedures found on your github repositories but it keeps failing with errors. Failure to build wheels for pycapnp error and subprocess errors. Can anyone help please. Do you have a newer version or something that I could use as I am trying to do some experiments on my PhD project. Any help please. Thanks

**Comment by FaisalAlshami** [comment]
Already I installed syft 0.8.0.post2, torch 2.0.1 and torchvision 0.15.2
and I got this problem :
AttributeError: module 'syft' has no attribute 'join_duet'

Please I need help
[image: image.png]

**Comment by bbyuksel** [comment]
import syft as sy
sy.load_lib("tenseal")
duet = sy.launch_duet(loopback=True)
duet = sy.launch_duet()

Hi there. When I run this script I got an error;
AttributeError: module 'syft' has no attribute 'load_lib'

Which updated library requirements or do I need to work with it?

**Comment by madhavajay** [comment]
@FaisalAlshami To use Duet you need a version of from around syft 0.3 - 0.5.
There won't really be anything you can do with Duet you can't do in Syft 0.8.3 so I would suggest migrating to that.

https://github.com/OpenMined/PySyft/tree/dev/notebooks/api/0.8
