### ISSUE TITLE
Problems with API Notebook 0.8 #3, Pointer = None

### ISSUE THREAD

**Issue by PalexGoneGit** [OpenMined/PySyft#8549]
In the example notebook (and my implementation with other data), I receive the following error relating to blob storage and pointers: No blob storage entry exists. Pointer = None is returned. I can not receive the result from the function.

## How to Reproduce
1. Execute Notebooks 1-3
2. The error is on Notebook 3

## Expected Behavior
To receive a pointer and to compute the result

## Screenshots
![Screenshot 2024-03-04 at 18 04 24](https://github.com/OpenMined/PySyft/assets/60147284/f1f7131e-dd0c-42d9-9e97-79620db0fcda)

## System Information
 Syft = 0.8.4

**Comment by koenvanderveen** [comment]
Hi, thanks for raising this. I am not able to reproduce though. Which version of the notebooks are you running? Can you try it from the 0.8.4 branch and see if the problem persists?

**Comment by PalexGoneGit** [comment]
Thanks @koenvanderveen . I tried redownloading the notebooks and it seems to seitch between this issue with my own data and Issue #8530 with the data provided in the notebooks. Will further investigate abd let you know!

**Comment by PalexGoneGit** [comment]
Hi @koenvanderveen, I just retested the recently updated notebooks. The issue is still the same as in #8530. Can confirm with both Notebook #1 and Notebook #3 run into issues for me (with opendp installed and imported). It's MacOS, if that matters. Attached both errors.

![Screenshot 2024-03-05 at 16 36 13](https://github.com/OpenMined/PySyft/assets/60147284/3f33b6cc-a457-42ca-beee-54fffddc926e)

![Screenshot 2024-03-05 at 16 32 26](https://github.com/OpenMined/PySyft/assets/60147284/ae8d352e-7ff2-4449-8b69-eff423115e63)

**Comment by koenvanderveen** [comment]
What is the .message (pointer.message in this case) property of the SyftError you are getting? Just to be completely sure its not an environment issue, if you import opendp from within the notebook that works?

**Comment by PalexGoneGit** [comment]
Unfortunately, it does not work when importing opendp, still.
'Exception encountered while running sum_trade_value_mil, please contact the Node Admin for more info.'

![Screenshot 2024-03-05 at 22 46 28](https://github.com/OpenMined/PySyft/assets/60147284/f7a037ff-9497-4c0c-9fc6-44e1d030d541)

**Comment by madhavajay** [comment]
@AlexAronikov are you able to tell us what version of python you are running also so I can try to replicate this.

**Comment by PalexGoneGit** [comment]
@madhavajay Thanks for your answer. It's Python 3.9.18. What version do you recommend?

**Comment by madhavajay** [comment]
@AlexAronikov I have replicated this issue. It isn't a bug per se, whats happening is there is an exception which gets logged but is not visible to the user which says `no module named 'opendp'`
<img width="828" alt="Screenshot 2024-03-07 at 10 14 47 am" src="https://github.com/OpenMined/PySyft/assets/2882739/9cba6e15-be7c-4d71-b309-d02b27546c27">

In CI we install syft with all the data science extras:
```
$ pip install syft[data_science]
```

However if you just install syft and use this notebook you won't have opendp.

You should be able to verify and fix with:
```
!pip list | grep opendp
```

```
!pip install opendp==0.8.0
```

And then restart your notebook and try again.

What we can do here is make that error more obvious. @koenvanderveen I think in this case printing out the exception makes sense because for the local user its their private access anyway, for the remote server its printing on the server and we capture that context and make it part of the protected logs as well.

**Comment by madhavajay** [comment]
After pip installing opendp.
<img width="769" alt="Screenshot 2024-03-07 at 10 15 53 am" src="https://github.com/OpenMined/PySyft/assets/2882739/82230599-119a-45f9-a8a9-daf664ae6004">

**Comment by PalexGoneGit** [comment]
Thanks @madhavajay ! The error mentioned before is fixed with your suggestions. The "No blob storage entry exists" error persists with my own data, though. Any suggestions on how to troubleshoot?

**Comment by madhavajay** [comment]
@AlexAronikov can you be a bit more specific about the blob storage issue? Can you give me the error message and how you got it so I can replicate it? If its unrelated you could always create a new issue.

**Comment by PalexGoneGit** [comment]
I don't seem to encounter this error anymore, probably a mistake from my side. Thank you!
