### ISSUE TITLE
PySyft in JupyterLite

### ISSUE THREAD

**Issue by petermchale** [OpenMined/PySyft#8703]
## Question
Can a data scientist run PySyft in JupyterLite?  

## Further Information
I'd like to create a web app in which a data scientist can conduct remote data science. JupyterLite is a new project that enables developers to run a Jupyter notebook in the browser. JupyterLite is extensible, e.g., one can install Python packages that get served as static web assets. Is it possible to install PySyft into JupyterLite so that a data scientist could conduct remote data science from his/her browser? 

## Screenshots
N/A

## System Information
N/A

**Comment by madhavajay** [comment]
@petermchale I have dreamed of doing this for a while. We need to do a few things to make it happen. 

The first thing is to check what dependencies would have issues installing and look to have them removed for a more lightweight client version of the syft library.

The DL libraries would have to be removed for now which is fine, but my main concern would be around things like pycapnp. We might need to setup some of our own wasm / pyodid package compilations but thats probably doable.

If you happen to have experience with this stuff let me know, otherwise ill speak to our team about when we might be able to prioritize this.

**Comment by petermchale** [comment]
Sorry, I don't have experience with this stuff.

**Comment by madhavajay** [comment]
@petermchale don't worry we will definitely be doing something in this vein soon. Ill discuss with the team and @leriomaggio

**Comment by petermchale** [comment]
@madhavajay : this is great news. I look forward to seeing a prototype. Best, Peter

**Comment by madhavajay** [comment]
@petermchale ill close this for now as its on our roadmap once we make our client library a little more flexible.
