### ISSUE TITLE
Implement Default resize Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#88]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, resize_() and resize_as_() should operate inline. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by aradhyamathur** [comment]
@iamtrask  i have added this functionality in my fork https://github.com/aradhyamathur/PySyft/commit/34e339c2e2e64b9120a6173714a290e9f75b8a28. I haven't opened the pull request since the circleCi is still giving some trouble, my last pull request is still pending from the same branch. I noticed that PyTorch resize allows users to increase and decrease the size without the loss of values. I am not sure how they are achieving this since numpy does not allow such reshape. Kindly review it once.

**Comment by aradhyamathur** [comment]
since travis worked i have added a pull request for the same.
