### ISSUE TITLE
Implement Default set Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#93]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, set_() should operate inline. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by sp4ke** [comment]
I will work on this one.

**Comment by sp4ke** [comment]
I have a few questions before moving forward. 

What does **should operate inline** mean ?

The [pytorch signature](http://pytorch.org/docs/master/tensors.html#torch.Tensor.set_) for this function is `set_(source=None, storage_offset=0, size=None, stride=None)` and the **source** parameter can be either a Tensor, or a Storage which is custom made by an underlying C extension

However since our tensor's internal storage is an ndarray the source is always going to be a Tensor right ? which means storage_offset and size are useless, or am I missing something ?

**Comment by sp4ke** [comment]
ping @iamtrask

**Comment by sp4ke** [comment]
@iamtrask can you give a bit more details how this method is supposed to behave ? There are many ways to implement this and I'm not sure if the signature needs to be the same as PyTorch
